
import time
import logging
from typing import Dict, List, Optional, Any
from pathlib import Path
from dotenv import load_dotenv
from dataclasses import dataclass

from pydantic import BaseModel, Field
from pydantic_ai import Agent

from .models import (
    BehaviorSynthesisResponse,
    ExpertFunction,
    StateDefinition,
    SpeciesConfiguration,
    ForceComputation,
    VectorExpression,
    IntegrationKernel
)
from ..debug.tracing import get_collector, LLMCallData
from .species_analyzer import SpeciesAnalyzer
from .species_manager import SpeciesManager
from .prompt_loader import get_prompt_loader

logger = logging.getLogger(__name__)


@dataclass
class Expert:
    name: str
    description: str
    code: str
    is_interaction: bool = False
    weight: float = 1.0
    
    def to_code(self) -> str:
        return self.code


class HelperFunction(BaseModel):
    """A helper function generated by the LLM."""
    name: str = Field(description="Name of the helper function")
    code: str = Field(description="The code of the helper function")


class TaichiCodeResponse(BaseModel):
    name: str
    description: str
    code: str
    is_interaction: bool = False
    helper_functions: Optional[List[HelperFunction]] = Field(default=None, description="Helper functions generated alongside the expert")


class InitializationResponse(BaseModel):
    name: str = Field(description="Name of the initialization kernel")
    description: str = Field(description="What this initialization does")
    code: str = Field(description="Complete Taichi kernel for initialization")
    init_type: str = Field(description="Type: random, grid, clustered, ring, wave, etc.")


class TemporalUpdateResponse(BaseModel):
    name: str = Field(description="Name of the temporal update kernel")
    description: str = Field(description="What this temporal update does")
    code: str = Field(description="Complete Taichi kernel for temporal updates")
    update_type: str = Field(description="Type: energy, oscillator, growth, day_night, etc.")


class UtilityExpertResponse(BaseModel):
    name: str = Field(description="Name of the utility function")
    description: str = Field(description="What this utility function does")
    code: str = Field(description="Complete @ti.func code without particle parameters")
    utility_type: str = Field(description="Type: temporal_update, state_update, helper, etc.")
    returns_value: bool = Field(default=False, description="Whether the function returns a value")


class ConfigurationResponse(BaseModel):
    species_count: int = Field(description="Number of species detected")
    particle_count: int = Field(description="Recommended particle count")
    config_code: str = Field(description="Python code to configure Tölvera parameters")


class StateField(BaseModel):
    name: str = Field(description="Name of the state field")
    category: str = Field(description="Category: 'global', 'particle', or 'species'")
    type: str = Field(description="Taichi type (e.g., 'ti.f32', 'ti.i32', 'ti.math.vec2')")
    min: Optional[float] = Field(default=None, description="Minimum value for numeric types")
    max: Optional[float] = Field(default=None, description="Maximum value for numeric types")
    description: str = Field(description="What this state represents")
    initial: Optional[float] = Field(default=None, description="Initial value")


class TemporalUpdateInfo(BaseModel):
    state_name: str = Field(description="Name of the state to update")
    update_expression: str = Field(description="Taichi expression for updating the state over time")
    description: str = Field(description="Description of the temporal behavior")


class StateAnalysisResponse(BaseModel):
    needs_states: bool = Field(description="Whether this behavior requires custom states")
    states: List[StateField] = Field(default_factory=list, description="List of states needed for this behavior")


class Synthesizer:
    
    def __init__(
        self,
        model_name: str = "gemini-2.0-flash",
        tolvera_instance=None,
        api_key: Optional[str] = None
    ):
        # Load environment variables
        self._load_env()
        
        self.model_name = model_name
        self.tv = tolvera_instance
        
        # Use model factory to create the appropriate model
        from .model_factory import ModelFactory
        self.model = ModelFactory.create_model(model_name, api_key)
        self.provider = ModelFactory.get_provider_for_model(model_name)
        logger.info(f"Synthesizer using provider '{self.provider}' with model '{model_name}'")
        
        # Initialize species components
        self.species_analyzer = SpeciesAnalyzer()
        self.species_manager = SpeciesManager(tolvera_instance) if tolvera_instance else None
        
        # Initialize prompt loader
        self.prompt_loader = get_prompt_loader()
        
        # Keep track of experts
        self.experts = []
        
    def _load_env(self):
        env_paths = [
            Path.cwd() / ".env",
            Path(__file__).parent.parent.parent.parent.parent / ".env",
        ]
        
        for env_path in env_paths:
            if env_path.exists():
                load_dotenv(env_path)
                break
    
    def _get_expert_type_guidance(self, expert_type: Optional[str]) -> str:
        """Get expert-type specific guidance for state analysis."""
        if not expert_type:
            return ""
            
        guidance_map = {
            'force': """
FORCE EXPERT CONTEXT:
Focus on physics-related states that affect forces:
- "particles chase food" → needs 'consumed' state (ti.i32) to mark eaten food
- "energy depletes over time" → needs 'energy' state (ti.f32) that affects movement
- "particles get tired" → needs 'energy' or 'stamina' state
- "magnetic attraction" → might need 'charge' state (ti.f32)
- "particles return home" → needs 'home_pos' state (ti.math.vec2)
""",
            'interaction': """
INTERACTION EXPERT CONTEXT:
Focus on relationship and detection states:
- "predator hunts prey" → needs 'hunt_radius' state (ti.f32) for detection range
- "particles form bonds" → needs 'bond_strength' or 'connection_count' states
- "species interact differently" → needs species-specific parameters
- "particles remember encounters" → needs 'last_interaction_time' state
""",
            'visual': """
VISUAL EXPERT CONTEXT:
Focus on animation and display states:
- "particles blink" → needs 'blink_timer' or 'blink_phase' state (ti.f32)
- "color changes over time" → needs 'color_phase' or 'hue_shift' state
- "particles pulse" → needs 'pulse_phase' state for animation
- "trails fade" → needs 'trail_intensity' state
""",
            'temporal_update': """
TEMPORAL UPDATE CONTEXT:
Focus on time-dependent state changes:
- "day/night cycle" → needs 'day_phase' state (ti.f32) with periodic updates
- "aging particles" → needs 'age' state (ti.f32) that increments
- "energy regeneration" → needs energy state with recovery rules
- "seasonal changes" → needs 'season' state with transitions
""",
            'utility': """
UTILITY EXPERT CONTEXT:
Focus on helper states and flags:
- "grid-based behavior" → needs 'grid_x', 'grid_y' states (ti.i32)
- "cellular automaton" → needs 'is_alive', 'neighbor_count' states
- "state machines" → needs 'current_state' enumeration
- "counters and timers" → needs accumulator states
"""
        }
        
        return guidance_map.get(expert_type, "")

    async def analyze_states_needed(
        self,
        description: str,
        expert_type: Optional[str] = None
    ) -> Dict[str, Any]:
        logger.info(f"Analyzing states needed for: {description} (type: {expert_type})")
        
        # Get trace collector
        collector = get_collector()
        
        # Build state analysis prompt with expert type context
        prompt = f"""Analyze what custom states (if any) are needed for this behavior: "{description}"

EXPERT TYPE: {expert_type}

The following properties are ALREADY AVAILABLE on every particle and should NOT be recreated:
- pos (ti.math.vec2): Position
- vel (ti.math.vec2): Velocity  
- mass (ti.f32): Mass
- size (ti.f32): Display size
- speed (ti.f32): Speed magnitude
- species (ti.i32): Species ID
- active (ti.f32): Activity level
- ppos, pvel: Previous position/velocity

Only create NEW states for properties that don't already exist.

{self._get_expert_type_guidance(expert_type)}

Consider:
1. Does it need to track time, phases, or system-wide parameters? → Add to global_states
2. Does it need per-particle memory or properties NOT listed above? → Add to particle_states  
3. Does it need species-specific configuration? → Add to species_states
4. Can it be implemented with just the existing properties? → Set needs_states: false"""
        
        # Load state analysis prompts using PromptLoader
        loader = get_prompt_loader()
        
        # Combine the state analysis prompts
        system_prompt_parts = [
            loader.load_prompt("synthesis/state_analysis_system.txt"),
            loader.load_prompt("synthesis/state_analysis_examples.txt"),
            loader.load_prompt("synthesis/state_analysis_criteria.txt", 
                              expert_type_guidance=self._get_expert_type_guidance(expert_type))
        ]
        
        system_prompt = "\n\n".join(system_prompt_parts)
        
        # Log the assembled prompt
        logger.info(f"[SYNTHESIZER] State Analysis System Prompt assembled: {len(system_prompt)} chars")
        logger.debug(f"[SYNTHESIZER] System prompt preview (first 500 chars): {system_prompt[:500]}")
        if logger.isEnabledFor(logging.DEBUG):
            # In debug mode, log the full prompt
            logger.debug(f"[SYNTHESIZER] Full system prompt:\n{system_prompt}")
        
        # Create structured agent for state analysis
        agent = Agent(
            self.model,
            output_type=StateAnalysisResponse,
            system_prompt=system_prompt
        )
        
        # Create trace node for state analysis
        with collector.trace_node("state_analysis", "state_analysis", 
                                 description=description) as analysis_node:
            try:
                # Create nested LLM call node
                with collector.trace_node("llm_state_analysis", "llm_call",
                                         model=self.model_name) as llm_node:
                    # Log the user prompt being sent
                    logger.info(f"[SYNTHESIZER] Running state analysis with user prompt: {len(prompt)} chars")
                    logger.debug(f"[SYNTHESIZER] User prompt: {prompt}")
                    
                    # Run state analysis with structured output
                    result = await agent.run(prompt)
                    state_analysis = result.output
                    
                    # Log LLM call details
                    if llm_node:
                        # Create LLM data
                        from ..debug.tracing import LLMCallData
                        if hasattr(agent, '_system_prompt'):
                            system_prompt = agent._system_prompt
                        elif hasattr(agent, 'system_prompt'):
                            system_prompt = str(agent.system_prompt)
                        else:
                            system_prompt = "State analysis prompt"
                        full_prompt = f"{system_prompt}\n\n{prompt}"
                        llm_data = LLMCallData(
                            model=self.model_name,
                            provider="gemini",
                            system_prompt=system_prompt,
                            user_prompt=prompt,
                            full_prompt=full_prompt,
                            raw_response=str(result.output),
                            parsed_response={
                                "needs_states": state_analysis.needs_states,
                                "states": [state.model_dump() for state in state_analysis.states]
                            }
                        )
                        llm_node.llm_call = llm_data
                
                # Count states by category - only if states are actually needed
                if state_analysis.needs_states and state_analysis.states:
                    global_count = sum(1 for s in state_analysis.states if s.category == 'global')
                    particle_count = sum(1 for s in state_analysis.states if s.category == 'particle')
                    species_count = sum(1 for s in state_analysis.states if s.category == 'species')
                else:
                    # No states needed, so all counts should be 0
                    global_count = 0
                    particle_count = 0
                    species_count = 0
                
                logger.info(f"State analysis: needs_states={state_analysis.needs_states}, "
                           f"global={global_count}, "
                           f"particle={particle_count}, "
                           f"species={species_count}")
                
                # Update trace node with results
                if analysis_node:
                    analysis_node.output_data = {
                        "needs_states": state_analysis.needs_states,
                        "global_states": global_count,
                        "particle_states": particle_count,
                        "species_states": species_count
                    }
            
                # Convert to StateDefinition objects
                states_dict = {
                    'global': {},
                    'particle': {},
                    'species': {}
                }
                
                # Process states from the list
                BUILTIN_PARTICLE_PROPS = {'pos', 'vel', 'mass', 'size', 'speed', 'species', 'active', 'ppos', 'pvel'}
                
                for state_info in state_analysis.states:
                    category = state_info.category
                    state_name = state_info.name
                    
                    # Skip built-in particle properties
                    if category == 'particle' and state_name.lower() in BUILTIN_PARTICLE_PROPS:
                        logger.warning(f"Skipping built-in particle property '{state_name}' from state analysis")
                        continue
                    
                    states_dict[category][state_name] = StateDefinition(
                        name=state_name,
                        category=category,
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                logger.info(f"States needed - Global: {len(states_dict['global'])}, "
                           f"Particle: {len(states_dict['particle'])}, "
                           f"Species: {len(states_dict['species'])}")
                
                return states_dict
                
            except Exception as e:
                logger.warning(f"State analysis failed: {e}, proceeding without custom states")
                return {'global': {}, 'particle': {}, 'species': {}}
    
    async def synthesize_behavior(
        self,
        description: str,
        available_states: Optional[Dict[str, List[str]]] = None,
        context: Optional[Dict[str, Any]] = None,
        expert_name: Optional[str] = None,
        skip_state_analysis: bool = False
    ) -> BehaviorSynthesisResponse:
        logger.info(f"Synthesizing: {description}")
        
        # Get trace collector
        collector = get_collector()
        
        # Skip state analysis if context already provides states
        if skip_state_analysis or (context and context.get('states_already_created')):
            logger.info("Skipping state analysis - states already created")
            states_analysis = {'global': {}, 'particle': {}, 'species': {}}
        else:
            # First, analyze what states are needed
            states_analysis = await self.analyze_states_needed(description)
        
        # Flatten state definitions for the response
        states_needed_list = []
        for category in ['global', 'particle', 'species']:
            if category in states_analysis:
                for state_def in states_analysis[category].values():
                    states_needed_list.append(state_def)
        
        # Update available_states to include both existing and new states
        if available_states is None:
            available_states = {'global': [], 'particle': [], 'species': [], 'temporal': []}
        else:
            # Ensure all categories exist
            for category in ['global', 'particle', 'species', 'temporal']:
                if category not in available_states:
                    available_states[category] = []
        
        # Add analyzed states to available states for prompt
        for category in ['global', 'particle', 'species', 'temporal']:
            if category in states_analysis:
                for state_name in states_analysis[category].keys():
                    if state_name not in available_states[category]:
                        available_states[category].append(state_name)
        
        # Analyze species from description
        species_info = self.species_analyzer.analyze(description)
        logger.info(f"Detected {species_info.total_count} species from description")
        
        # Get species context for prompt
        species_context = ""
        if self.species_manager:
            species_context = self.species_manager.get_species_context_for_prompts(species_info)
        
        # Log available states for debugging
        logger.info(f"Available states for synthesis: {available_states}")
        
        # Build comprehensive prompt using enhanced prompt_loader with dynamic context selection
        base_prompt = await self.prompt_loader.build_prompt_with_dynamic_context(
            description=description,
            expert_type="force",  # Default expert type
            available_states=available_states,
            additional_context=context
        )
        
        # Add species context if available
        if species_context:
            system_prompt = base_prompt + f"\n\n## SPECIES CONTEXT\n{species_context}\n"
        else:
            system_prompt = base_prompt
        
        # Add specific instructions for expert functions using PromptLoader
        loader = get_prompt_loader()
        
        # Load expert synthesis requirements and critical rules
        expert_requirements = loader.load_prompt("synthesis/expert_synthesis_requirements.txt", 
                                                 species_count=species_info.total_count - 1)
        taichi_rules = loader.load_prompt("synthesis/taichi_critical_rules.txt")
        
        system_prompt += f"\n\n{expert_requirements}\n\n{taichi_rules}"
        
        # Add specific expert name requirement if provided
        if expert_name:
            system_prompt += f"\n\nIMPORTANT: The function MUST be named '{expert_name}' exactly."
        
        # Initialize applies_to for later use
        applies_to = None
        
        # Check if this is a visual/drawing expert
        is_visual_expert = False
        if context and context.get('component'):
            component = context['component']
            if hasattr(component, 'expert_type') and component.expert_type == 'visual':
                is_visual_expert = True
                system_prompt += "\n\nCRITICAL: This is a VISUAL/DRAWING expert!"
                system_prompt += "\n- DO NOT return any force vector"
                system_prompt += "\n- DO NOT include '-> ti.math.vec2' in the function signature"
                system_prompt += "\n- Just perform drawing operations and end the function"
                system_prompt += "\n- Use 'if particle_idx == 0:' to draw only once per frame"
                
                # Add correct drawing API reference
                from ..context.drawing_patterns import DRAWING_API_REFERENCE
                system_prompt += "\n\nCORRECT TÖLVERA PIXELS API SIGNATURES:"
                system_prompt += "\n" + DRAWING_API_REFERENCE
                system_prompt += "\n\nIMPORTANT: Use EXACT function signatures shown above!"
                system_prompt += "\nDO NOT use incorrect signatures like tv.px.triangle(x1, y1, x2, y2, x3, y3, color)"
                system_prompt += "\nUSE CORRECT signatures like tv.px.triangle(a: vec2, b: vec2, c: vec2, rgba: vec4)"
                
                # CRITICAL: Add available states information for visual experts
                system_prompt += "\n\n## AVAILABLE STATES FOR VISUAL EXPERTS"
                system_prompt += "\nVisual experts can access these states for dynamic drawing effects:"
                
                # IMPORTANT: Order matters - check temporal first for animation states
                if available_states.get('temporal'):
                    # Temporal states are now mapped to global
                    # (Already handled in global states above)
                    system_prompt += "\nUSE THESE for time-based animations (phase, day_phase, time, etc.)"
                    system_prompt += "\nCRITICAL: For ANY oscillating/blinking/appearing/disappearing effects, use temporal states!"
                
                if available_states.get('global'):
                    system_prompt += f"\n\nGlobal states: {', '.join(available_states['global'])}"
                    system_prompt += "\nAccess with: tv.s.llm_global.field[0].STATE_NAME"
                    system_prompt += "\nNOTE: These are for global parameters, NOT for animation timing!"
                
                if available_states.get('particle'):
                    system_prompt += f"\n\nParticle states: {', '.join(available_states['particle'])}"
                    system_prompt += "\nAccess with: tv.s.llm_particle.field[particle_idx].STATE_NAME"
                    system_prompt += "\nNOTE: For drawing, you may want to loop through particles or use specific indices"
                
                if not any(available_states.values()):
                    system_prompt += "\n\nNO CUSTOM STATES AVAILABLE - use frame counter for animations:"
                    system_prompt += "\n  frame = tv.ctx.i[None]"
                    system_prompt += "\n  phase = (frame % period) / period  # For oscillations"
                else:
                    system_prompt += "\n\nIMPORTANT: Only use the states listed above! If a state doesn't exist, use frame counter instead."
        
        # If context indicates this expert is for a specific species, tell synthesizer not to check species
        if context and context.get('component') and hasattr(context['component'], 'applies_to_species'):
            applies_to = context['component'].applies_to_species
            if applies_to is not None:
                system_prompt += f"\n\nCRITICAL: This expert is specifically for species {applies_to}."
                system_prompt += "\nDO NOT check species inside the expert function!"
                system_prompt += "\nThe integration kernel will handle applying this expert only to the correct species."
                system_prompt += "\nWrite the expert assuming it's ONLY called for the intended species."
        else:
            # Fallback: Check if description mentions specific species
            desc_lower = description.lower()
            species_mentions = []
            if 'species 0' in desc_lower or 'species one' in desc_lower or 'first species' in desc_lower:
                species_mentions.append(0)
            if 'species 1' in desc_lower or 'species two' in desc_lower or 'second species' in desc_lower:
                species_mentions.append(1)
            if 'species 2' in desc_lower or 'species three' in desc_lower or 'third species' in desc_lower:
                species_mentions.append(2)
            
            # Save detected species for later use
            if species_mentions:
                applies_to = species_mentions  # Set applies_to for use later
            else:
                applies_to = None
            
            if len(species_mentions) == 1:
                system_prompt += f"\n\nDETECTED: This behavior is for species {species_mentions[0]} specifically."
                system_prompt += f"\nGenerate the expert to ONLY apply force when species == {species_mentions[0]}."
                system_prompt += "\nUse this pattern:"
                system_prompt += "\n```python"
                system_prompt += "\nforce = ti.math.vec2(0.0, 0.0)"
                system_prompt += f"\nif species == {species_mentions[0]}:"
                system_prompt += "\n    # Calculate and set force here"
                system_prompt += "\n    force = ..."
                system_prompt += "\nreturn force"
                system_prompt += "\n```"
        
        # Add previously synthesized helpers if provided in context
        if context and context.get('synthesized_helpers'):
            system_prompt += "\n\n## AVAILABLE HELPER FUNCTIONS FROM PREVIOUS EXPERTS\n"
            system_prompt += "The following helper functions have already been synthesized and are available:\n"
            for helper_name, helper_code in context['synthesized_helpers'].items():
                system_prompt += f"\n### {helper_name}:\n```python\n{helper_code}\n```\n"
            system_prompt += "\nYou can CALL these existing helpers in your expert.\n"
            system_prompt += "You can also generate NEW helpers if needed for your specific expert.\n"
        
        # Add pattern type context if provided
        if context and context.get('pattern_type'):
            system_prompt += "\n\n## PATTERN TYPE\n"
            system_prompt += f"This behavior is part of a {context['pattern_type']} pattern.\n"
            if context['pattern_type'] == 'cellular_automaton':
                system_prompt += "Use count_neighbors() and apply_rules() helpers for Game of Life logic.\n"
            elif context['pattern_type'] == 'physarum':
                system_prompt += "Use sense_pheromone(), deposit_trail(), and turn_toward_signal() for slime mold behavior.\n"
            elif context['pattern_type'] == 'ecosystem':
                system_prompt += "Use find_nearest_prey(), find_nearest_predator(), and transfer_energy() for predator-prey dynamics.\n"
        
        # Add context constraints if provided
        if context and context.get('constraints'):
            system_prompt += "\n\n## CONTEXT CONSTRAINTS\n"
            system_prompt += "The following constraints MUST be respected in your implementation:\n"
            for constraint in context['constraints']:
                system_prompt += f"- {constraint}\n"
        
        # Add previous expert information if provided
        if context and context.get('previous_experts'):
            system_prompt += "\n\n## PREVIOUS EXPERTS\n"
            system_prompt += "The following experts have already been implemented:\n"
            for prev in context['previous_experts']:
                system_prompt += f"- {prev['name']} ({prev['type']}): {prev.get('context', {})}\n"
        
        # Add shared parameters if provided
        if context and context.get('shared_parameters'):
            system_prompt += "\n\n## SHARED PARAMETERS\n"
            system_prompt += "Use these parameter values consistently across your implementation:\n"
            for param, value in context['shared_parameters'].items():
                system_prompt += f"- {param}: {value}\n"
        
        # Add explicit state usage instructions when states are available
        if any(available_states.values()):
            system_prompt += """

## IMPORTANT: USE THE AVAILABLE STATES
The following states are available and MUST be used in your implementation:
"""
            if available_states.get('global'):
                system_prompt += f"\nGlobal states: {', '.join(available_states['global'])}"
                system_prompt += "\nAccess with: tv.s.llm_global.field[0].STATE_NAME"
            if available_states.get('particle'):
                system_prompt += f"\nParticle states: {', '.join(available_states['particle'])}"
                system_prompt += "\nAccess with: tv.s.llm_particle.field[particle_idx].STATE_NAME"
            if available_states.get('species'):
                system_prompt += f"\nSpecies states: {', '.join(available_states['species'])}"
                system_prompt += "\nAccess with: tv.s.llm_species.field[species].STATE_NAME"
            # Temporal states are now part of global states (removed temporal category)
            
            system_prompt += "\n\nYour implementation MUST use these states to implement the requested behavior."
        
        # Log the assembled system prompt
        logger.info(f"[SYNTHESIZER] Expert Synthesis System Prompt assembled: {len(system_prompt)} chars")
        logger.debug(f"[SYNTHESIZER] System prompt preview (first 500 chars): {system_prompt[:500]}")
        if logger.isEnabledFor(logging.DEBUG):
            # In debug mode, log the full prompt
            logger.debug(f"[SYNTHESIZER] Full system prompt:\n{system_prompt}")
        
        # Create agent for this synthesis
        agent = Agent(
            self.model,
            output_type=TaichiCodeResponse,
            system_prompt=system_prompt
        )
        
        # User prompt
        if expert_name:
            user_prompt = f'Generate expert function named "{expert_name}" for: "{description}"'
        else:
            user_prompt = f'Generate expert function for: "{description}"'
        
        # Add behavioral guidance if provided (high-level, not specific implementation)
        if context and context.get('component_behavioral_guidance'):
            user_prompt += f"\n\nBehavioral guidance: {context['component_behavioral_guidance']}"
        elif context and context.get('component_implementation'):
            # Fallback for backward compatibility
            user_prompt += f"\n\nBehavioral guidance: {context['component_implementation']}"
        
        # Create LLM trace node
        with collector.trace_node("llm_synthesis", "llm_call", 
                                 description=description,
                                 expert_name=expert_name if expert_name else "",
                                 model=self.model_name) as llm_node:
            
            # Create LLM call data
            llm_data = LLMCallData(
                model=self.model_name,
                provider="gemini",
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                full_prompt=f"System: {system_prompt}\n\nUser: {user_prompt}"
            )
            
            try:
                # Log the user prompt being sent
                logger.info(f"[SYNTHESIZER] Running expert synthesis with user prompt: {len(user_prompt)} chars")
                logger.debug(f"[SYNTHESIZER] User prompt: {user_prompt}")
                
                # Time the API call
                start_time = time.time()
                result = await agent.run(user_prompt)
                api_duration = (time.time() - start_time) * 1000
                
                expert_data = result.output
                
                # Capture the response
                llm_data.api_call_ms = api_duration
                llm_data.raw_response = str(result)
                llm_data.parsed_response = {
                    "name": expert_data.name,
                    "description": expert_data.description,
                    "code": expert_data.code,
                    "is_interaction": expert_data.is_interaction if hasattr(expert_data, 'is_interaction') else False,
                    "helper_functions": getattr(expert_data, 'helper_functions', {}) if hasattr(expert_data, 'helper_functions') else {}
                }
                
                # Update trace node if it exists
                if llm_node:
                    llm_node.llm_call = llm_data
                    llm_node.output_data = {
                        "expert_name": expert_data.name,
                        "code_length": len(expert_data.code),
                        "is_interaction": expert_data.is_interaction
                    }
                    # Update metadata for console tracer
                    llm_node.metadata.update({
                        "model": self.model_name,
                        "prompt_length": len(system_prompt + user_prompt),
                        "response_length": len(str(result))
                    })
                
                # Create minimal expert
                expert = Expert(
                    name=expert_data.name,
                    description=expert_data.description,
                    code=expert_data.code,
                    is_interaction=expert_data.is_interaction
                )
                
                # Store it
                self.experts.append(expert)
                
                # Create proper response structure
                # We need to create the ExpertFunction with proper computation
                force_expr = VectorExpression(x="0.0", y="0.0")
                computation = ForceComputation(
                    base_force=force_expr,
                    description=expert.description if hasattr(expert, 'description') else ""
                )
                
                # Create ExpertFunction with custom to_code
                class CustomExpertFunction(ExpertFunction):
                    def __init__(self, expert: Expert, applies_to_species=None):
                        super().__init__(
                            name=expert.name,
                            description=expert.description,
                            is_interaction=expert.is_interaction,
                            computation=computation,
                            weight=expert.weight,
                            applies_to_species=applies_to_species
                        )
                        self._expert = expert
                    
                    def to_code(self) -> str:
                        return self._expert.code
                
                # Check if this expert applies to specific species based on fallback detection
                applies_to_species = applies_to if applies_to else None
                expert_func = CustomExpertFunction(expert, applies_to_species)
                
                # Create integration kernel
                kernel = IntegrationKernel(
                    single_experts=[expert.name] if not expert.is_interaction else [],
                    interaction_experts=[expert.name] if expert.is_interaction else []
                )
                
                # Create species configuration with analyzed data
                species_config = SpeciesConfiguration(
                    species_ids=species_info.species_ids if species_info.species_ids else list(range(species_info.total_count)),
                    species_names=species_info.species_names,
                    interaction_pairs=species_info.interaction_pairs,
                    species_behaviors=species_info.species_behaviors,
                    requires_all_species=species_info.requires_all_species,
                    colors={i: self.species_analyzer.get_color_for_species(i, species_info) 
                           for i in range(species_info.total_count)}
                )
                
                # Temporal updates removed - handled by individual experts
                temporal_update = None
                
                # Create response with helper functions if any
                response = BehaviorSynthesisResponse(
                    experts=[expert_func],
                    states_needed=states_needed_list,
                    species_config=species_config,
                    integration_kernel=kernel,
                    temporal_update=temporal_update
                )
                
                # Add helper functions to response if generated
                # Note: helper_functions is a Dict field which Gemini API strips, so we need to check carefully
                if hasattr(expert_data, 'helper_functions') and expert_data.helper_functions:
                    response.helper_functions = {h.name: h.code for h in expert_data.helper_functions}
                
                return response
                
            except Exception as e:
                logger.error(f"Synthesis failed: {e}")
                logger.error("Full traceback:", exc_info=True)
                # Update trace node with error if it exists
                if llm_node:
                    llm_node.error = str(e)
                    llm_node.status = "error"
                # Return default
                return self._default_response()
    
    def _default_response(self) -> BehaviorSynthesisResponse:
        
        code = """@ti.func
def drift(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    t = ti.cast(tv.ctx.i[None], ti.f32) * 0.01
    return ti.math.vec2(ti.sin(t) * 30.0, ti.cos(t) * 30.0)"""
        
        expert = Expert(
            name="drift",
            description="Simple drift",
            code=code
        )
        
        # Create proper structure
        force_expr = VectorExpression(x="0.0", y="0.0")
        computation = ForceComputation(expression=force_expr, description="drift")
        
        class CustomExpertFunction(ExpertFunction):
            def __init__(self, expert: Expert, applies_to_species=None):
                super().__init__(
                    name=expert.name,
                    description=expert.description,
                    is_interaction=False,
                    computation=computation,
                    weight=1.0,
                    applies_to_species=applies_to_species
                )
                self._expert = expert
            
            def to_code(self) -> str:
                return self._expert.code
        
        # Create integration kernel
        kernel = IntegrationKernel(
            single_experts=[expert.name],
            interaction_experts=[]
        )
        
        return BehaviorSynthesisResponse(
            experts=[CustomExpertFunction(expert, applies_to_species=None)],
            states_needed=[],
            species_config=SpeciesConfiguration(species_ids=[0]),
            integration_kernel=kernel
        )
    
    async def synthesize_initialization(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> InitializationResponse:
        """Synthesize initialization kernel based on behavior description."""
        
        # Build initialization-specific prompt using basic template
        prompt = f"""You are a Taichi expert synthesizing particle initialization code for Tölvera.

Generate a complete @ti.kernel function that initializes particles based on: {description}

IMPORTANT:
- Set tv.p.field[i].active = 1.0 for active particles
- ALWAYS set tv.p.field[i].speed = 20.0 for movement scaling
- Particle size should be 5.0-10.0 for visibility
- Species ID must be within range [0, tv.sn-1]
- Use ti.random() for randomness, not Python's random
- Initialize velocities appropriate to behavior type"""
        
        # Add specific instructions for initialization
        system_prompt = f"""You are a Taichi expert synthesizing particle initialization code for Tölvera.
        
{prompt}

Generate a complete @ti.kernel function that initializes particles.
The function should be named 'init_particles' or similar.

IMPORTANT:
- Set tv.p.field[i].active = 1.0 for active particles
- ALWAYS set tv.p.field[i].speed = 20.0 for movement scaling
- Particle size should be 5.0-10.0 for visibility
- Species ID must be within range [0, tv.sn-1]
- Use ti.random() for randomness, not Python's random
- Initialize velocities appropriate to behavior type
"""
        
        if species_config:
            system_prompt += "\nSpecies Information:\n"
            system_prompt += f"- Total species: {len(species_config.species_ids)}\n"
            if species_config.species_names:
                for sid, name in species_config.species_names.items():
                    system_prompt += f"- Species {sid}: {name}\n"
        
        # Create agent for initialization synthesis
        agent = Agent(
            self.model,
            output_type=InitializationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize initialization
        result = await agent.run(description)
        
        return result.output
    
    async def synthesize_temporal_update(
        self,
        description: str,
        available_states: Dict[str, List[str]],
        context: Optional[Dict[str, Any]] = None
    ) -> TemporalUpdateResponse:
        """Synthesize temporal update kernel based on behavior description."""
        
        # Build temporal-specific prompt using basic template
        prompt = f"""You are a Taichi expert synthesizing temporal state updates for Tölvera based on: {description}

TEMPORAL UPDATE GUIDELINES:
1. For states that change over time:
   - energy: Deplete based on activity (vel.norm()), regenerate when resting
   - age: Increment each frame, handle lifecycle transitions
   - phase: Update based on frequency, handle wrapping
   - temperature: Apply cooling/heating with Newton's law
   - resources: Consume based on behavior, regenerate conditionally

2. Update rates based on description:
   - "slowly" → multiply by 0.999 or add/subtract 0.001
   - "gradually" → multiply by 0.99 or add/subtract 0.01
   - "quickly" → multiply by 0.95 or add/subtract 0.05
   - "rapidly" → multiply by 0.9 or add/subtract 0.1

IMPORTANT:
- Access states via tv.s.llm_particle.field[i].STATE_NAME
- Always clamp values to their valid ranges
- Only set active = 0.0 when particle truly dies (energy=0, max age)
- Consider species-specific dynamics where appropriate"""
        
        # Format available states with temporal info
        state_info = "Available States:\n"
        temporal_states = []
        
        if 'particle' in available_states:
            state_info += f"Particle states: {', '.join(available_states['particle'])}\n"
            # Identify temporal states
            for state in available_states['particle']:
                if state in ['energy', 'age', 'phase', 'temperature', 'resources']:
                    temporal_states.append(state)
        
        if 'global' in available_states:
            state_info += f"Global states: {', '.join(available_states['global'])}\n"
        
        if 'species' in available_states:
            state_info += f"Species states: {', '.join(available_states['species'])}\n"
        
        # Temporal states are now part of global states
        # (Already included in global states above)
            # All temporal states should be included
            temporal_states.extend(available_states['temporal'])
        
        if temporal_states:
            state_info += f"\nTemporal states detected: {', '.join(temporal_states)}\n"
        
        # Enhanced system prompt with temporal guidance
        system_prompt = f"""You are a Taichi expert synthesizing temporal state updates for Tölvera.
        
{prompt}

{state_info}

Generate a complete @ti.kernel function that updates states over time.
The function should be named 'update_temporal_states'.

TEMPORAL UPDATE GUIDELINES:
1. For states that change over time:
   - energy: Deplete based on activity (vel.norm()), regenerate when resting
   - age: Increment each frame, handle lifecycle transitions
   - phase: Update based on frequency, handle wrapping
   - temperature: Apply cooling/heating with Newton's law
   - resources: Consume based on behavior, regenerate conditionally

2. Update rates based on description:
   - "slowly" → multiply by 0.999 or add/subtract 0.001
   - "gradually" → multiply by 0.99 or add/subtract 0.01
   - "quickly" → multiply by 0.95 or add/subtract 0.05
   - "rapidly" → multiply by 0.9 or add/subtract 0.1

3. Context-aware updates:
   - Make updates dependent on particle state (species, velocity, position)
   - Different species can have different update rates
   - Consider behavioral coupling (e.g., low energy affects movement)

4. Implementation structure:
   ```python
   @ti.kernel
   def update_temporal_states():
       frame = tv.ctx.i[None]
       dt = 1.0 / 60.0  # 60 FPS
       
       # Update particle states
       for i in range(tv.pn):
           if tv.p.field[i].active > 0:
               # Get states
               # Apply updates
               # Clamp values
               # Apply behavioral effects
   ```

IMPORTANT:
- Access states via tv.s.llm_particle.field[i].STATE_NAME
- Always clamp values to their valid ranges
- Only set active = 0.0 when particle truly dies (energy=0, max age)
- Consider species-specific dynamics where appropriate
"""
        
        # Add behavioral context if provided
        if context:
            if context.get('behavior_description'):
                system_prompt += f"\nBehavior Context: {context['behavior_description']}\n"
            if context.get('temporal_requirements'):
                system_prompt += f"\nTemporal Requirements: {context['temporal_requirements']}\n"
        
        # Create agent for temporal synthesis
        agent = Agent(
            self.model,
            output_type=TemporalUpdateResponse,
            system_prompt=system_prompt
        )
        
        # Generate prompt with specific temporal focus
        user_prompt = f"""Generate temporal update kernel for: {description}
        
Focus on these aspects:
1. Identify which states need temporal updates
2. Determine appropriate update rates from the description
3. Implement species-specific updates if multiple species exist
4. Add behavioral coupling where states affect particle behavior
5. Handle edge cases (death, regeneration, phase wrapping)
"""
        
        # Synthesize temporal update
        result = await agent.run(user_prompt)
        
        return result.output
    
    async def synthesize_configuration(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None
    ) -> ConfigurationResponse:
        """Synthesize Tölvera configuration based on behavior description."""
        
        system_prompt = """You are configuring Tölvera parameters based on the behavior description.
        
Generate Python code that sets up the configuration dictionary for Tölvera.
The code should define kwargs overrides based on the detected behavior type.

Example output:
```python
# Configuration for ecosystem simulation
config = {
    'sn': 2,  # 2 species detected
    'pn': 800,  # Good for ecosystem
    'width': 1920,
    'height': 1080
}
```

Consider:
- Species count from description
- Appropriate particle count for behavior type
- Screen dimensions
"""
        
        if species_config:
            system_prompt += f"\nDetected {len(species_config.species_ids)} species from description.\n"
        
        # Create agent for configuration
        agent = Agent(
            self.model,
            output_type=ConfigurationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize configuration
        result = await agent.run(description)
        
        return result.output
    
    async def synthesize_utility_expert(
        self,
        description: str,
        available_states: Dict[str, List[str]],
        context: Optional[Dict[str, Any]] = None,
        expert_type: str = 'utility'
    ) -> UtilityExpertResponse:
        """Synthesize a utility expert function that doesn't take particle parameters."""
        
        logger.info(f"Synthesizing utility expert ({expert_type}): {description}")
        
        # States should already be created by BehaviorAgent before we get here
        # Just use the available_states that were passed in
        logger.info(f"Using pre-created states: {available_states}")
        
        # Build utility-specific prompt using basic template
        prompt = f"""You are a Taichi expert synthesizing {expert_type} functions for Tölvera based on: {description}

UNIVERSAL UTILITY FUNCTION RULES:
1. The function should NOT take particle parameters (pos, vel, mass, species, particle_idx)
2. Most utility functions take NO parameters at all: @ti.func def expert_name():
3. If parameters are needed, use only what's necessary (e.g., dt for time-based updates)
4. Access states directly via tv.s.llm_particle.field[i] or tv.s.llm_global.field[0]
5. Do NOT return force vectors (ti.math.vec2 or ti.Vector)
6. Most utility functions have NO return statement (void functions)
7. Use @ti.func decorator"""
        
        # Format available states
        state_info = "Available States:\n"
        if 'particle' in available_states:
            state_info += f"Particle states: {', '.join(available_states['particle'])}\n"
        if 'global' in available_states:
            state_info += f"Global states: {', '.join(available_states['global'])}\n"
        if 'species' in available_states:
            state_info += f"Species states: {', '.join(available_states['species'])}\n"
        # Temporal states are now part of global states
        # (Already included in global states above)
        
        # Build expert-type specific guidance
        expert_guidance = ""
        if expert_type == 'temporal_update':
            expert_guidance = """
TEMPORAL UPDATE SPECIFIC RULES:
- This is a TEMPORAL UPDATE function - it updates states over time
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- Access time-based states from global: tv.s.llm_global.field[0].STATE_NAME  # (day_phase, time, etc.)
- Common pattern: increment/decrement state values over time
- Example: day_phase = (day_phase + 0.001) % 1.0

WRONG TEMPORAL UPDATE (DO NOT GENERATE):
@ti.func
def expert_name(pos, vel, mass, species, particle_idx) -> ti.math.vec2:
    # This is COMPLETELY WRONG for temporal updates!

CORRECT TEMPORAL UPDATE (GENERATE THIS):
@ti.func
def expert_name():
    # Update time-based state - NO parameters, NO return
    tv.s.llm_global.field[0].day_phase += 0.001
    if tv.s.llm_global.field[0].day_phase > 1.0:
        tv.s.llm_global.field[0].day_phase = 0.0"""
        
        elif expert_type == 'state_update':
            expert_guidance = """
STATE UPDATE SPECIFIC RULES:
- This is a STATE UPDATE function - it modifies particle or global states
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- Loop over particles internally if needed: for i in range(tv.pn):
- Access particle states: tv.s.llm_particle.field[i].STATE_NAME

CORRECT STATE UPDATE (GENERATE THIS):
@ti.func
def expert_name():
    # Update states - NO parameters, NO return
    for i in range(tv.pn):
        if tv.p.field[i].active > 0:
            tv.s.llm_particle.field[i].energy -= 0.1"""
            
        elif expert_type == 'visual':
            expert_guidance = f"""
VISUAL/DRAWING EXPERT SPECIFIC RULES:
- This is a VISUAL/DRAWING function - it creates visual effects
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- DO NOT IMPORT TAICHI - it's already imported at the top of the file
- Use Pixels API: tv.px.rect(), tv.px.circle(), tv.px.line()
- Colors are ti.math.vec4(r, g, b, a) with values 0.0-1.0

CRITICAL STATE ACCESS RULES:
{state_info}

IMPORTANT: You can ONLY use the states listed above! Access patterns:
- Time-based states: tv.s.llm_global.field[0].STATE_NAME (for animations/time like day_phase, time, etc.)
- Global states: tv.s.llm_global.field[0].STATE_NAME (for global parameters)
- Particle states: tv.s.llm_particle.field[i].STATE_NAME (per-particle data)
- NEVER use tv.s.time[None] or any other made-up state access
- NEVER use llm_global for temporal/animation states!

For time-based visual effects (appearing/disappearing, pulsing, oscillating):
1. FIRST check what temporal states are ACTUALLY available from the list above
   - If 'temporal' states exist in the list, use ONLY those exact state names
   - Example: If 'phase' is listed in global states, use: tv.s.llm_global.field[0].phase
   - CRITICAL: ALL time-based states are now in llm_global!
2. If NO temporal states are available, use frame counter:
   - Access with: tv.ctx.i[None]
   - Example: visibility = ti.sin(ti.cast(tv.ctx.i[None], ti.f32) / period * 2 * ti.math.pi) > 0.0

CORRECT VISUAL EXPERT (WITH TEMPORAL STATE):
@ti.func
def expert_blinking_rectangle():
    # Use time-based state from global states
    time = tv.s.llm_global.field[0].time  # If 'time' is in global states list
    period = 2.5  # seconds
    visibility = ti.sin(2 * ti.math.pi * time / period) > 0.0
    if visibility:
        tv.px.rect(tv.x//2-50, tv.y//2-25, 100, 50, ti.math.vec4(1.0, 0.0, 0.0, 1.0))

CORRECT VISUAL EXPERT (WITHOUT TEMPORAL STATE):
@ti.func
def expert_blinking_rectangle():
    # Use frame counter as fallback
    frame = tv.ctx.i[None]
    period = 2.5 * 60  # 2.5 seconds at 60 FPS
    visibility = ti.sin(ti.cast(frame, ti.f32) / period * 2 * ti.math.pi) > 0.0
    if visibility:
        tv.px.rect(tv.x//2-50, tv.y//2-25, 100, 50, ti.math.vec4(1.0, 0.0, 0.0, 1.0))"""

        # System prompt for utility experts
        system_prompt = f"""You are a Taichi expert synthesizing {expert_type} functions for Tölvera.
        
{prompt}

{state_info}

Generate a @ti.func utility function based on the description.

{expert_guidance}

UNIVERSAL UTILITY FUNCTION RULES:
1. The function should NOT take particle parameters (pos, vel, mass, species, particle_idx)
2. Most utility functions take NO parameters at all: @ti.func def expert_name():
3. If parameters are needed, use only what's necessary (e.g., dt for time-based updates)
4. Access states directly via tv.s.llm_particle.field[i] or tv.s.llm_global.field[0]
5. Do NOT return force vectors (ti.math.vec2 or ti.Vector)
6. Most utility functions have NO return statement (void functions)
7. Use @ti.func decorator

CORRECT Examples:
@ti.func
def expert_day_phase_update():
    # Update global day phase - NO parameters, NO return
    tv.s.llm_global.field[0].day_phase += 0.001
    if tv.s.llm_global.field[0].day_phase > 1.0:
        tv.s.llm_global.field[0].day_phase = 0.0

@ti.func  
def expert_energy_depletion():
    # Deplete energy for all particles - NO parameters, NO return
    for i in range(tv.pn):
        if tv.p.field[i].active > 0:
            tv.s.llm_particle.field[i].energy -= 0.1
            if tv.s.llm_particle.field[i].energy < 0:
                tv.p.field[i].active = 0.0

The function name should start with 'expert_' followed by a descriptive name.
"""
        
        user_prompt = f"""Generate a utility expert function for: {description}

CRITICAL: The function MUST have this EXACT signature pattern:
@ti.func
def expert_{{function_name}}():
    # NO parameters in the function signature
    # Access states directly: tv.s.llm_global.field[0].day_phase  # time-based states are global
    # NO return statement (void function)
    
DO NOT include: pos, vel, mass, species, particle_idx parameters
DO NOT include: return ti.math.vec2(...) or any force return"""
        
        # Create agent for utility expert synthesis
        agent = Agent(
            self.model,
            output_type=UtilityExpertResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize utility expert
        result = await agent.run(user_prompt)
        
        return result.output
