
import time
import logging
from typing import Dict, List, Optional, Any
from pathlib import Path
from dotenv import load_dotenv
from dataclasses import dataclass

from pydantic import BaseModel, Field
from pydantic_ai import Agent

from .models import (
    BehaviorSynthesisResponse,
    ExpertFunction,
    StateDefinition,
    SpeciesConfiguration,
    ForceComputation,
    VectorExpression,
    IntegrationKernel
)
from ..debug.tracing import get_collector, LLMCallData
from .species_analyzer import SpeciesAnalyzer
from .species_manager import SpeciesManager
from .prompts import ContextAwarePromptBuilder

logger = logging.getLogger(__name__)


@dataclass
class Expert:
    name: str
    description: str
    code: str
    is_interaction: bool = False
    weight: float = 1.0
    
    def to_code(self) -> str:
        return self.code


class HelperFunction(BaseModel):
    """A helper function generated by the LLM."""
    name: str = Field(description="Name of the helper function")
    code: str = Field(description="The code of the helper function")


class TaichiCodeResponse(BaseModel):
    name: str
    description: str
    code: str
    is_interaction: bool = False
    helper_functions: Optional[List[HelperFunction]] = Field(default=None, description="Helper functions generated alongside the expert")


class InitializationResponse(BaseModel):
    name: str = Field(description="Name of the initialization kernel")
    description: str = Field(description="What this initialization does")
    code: str = Field(description="Complete Taichi kernel for initialization")
    init_type: str = Field(description="Type: random, grid, clustered, ring, wave, etc.")


class TemporalUpdateResponse(BaseModel):
    name: str = Field(description="Name of the temporal update kernel")
    description: str = Field(description="What this temporal update does")
    code: str = Field(description="Complete Taichi kernel for temporal updates")
    update_type: str = Field(description="Type: energy, oscillator, growth, day_night, etc.")


class UtilityExpertResponse(BaseModel):
    name: str = Field(description="Name of the utility function")
    description: str = Field(description="What this utility function does")
    code: str = Field(description="Complete @ti.func code without particle parameters")
    utility_type: str = Field(description="Type: temporal_update, state_update, helper, etc.")
    returns_value: bool = Field(default=False, description="Whether the function returns a value")


class ConfigurationResponse(BaseModel):
    species_count: int = Field(description="Number of species detected")
    particle_count: int = Field(description="Recommended particle count")
    config_code: str = Field(description="Python code to configure Tölvera parameters")


class StateField(BaseModel):
    name: str = Field(description="Name of the state field")
    type: str = Field(description="Taichi type (e.g., 'ti.f32', 'ti.i32', 'ti.math.vec2')")
    min: Optional[float] = Field(None, description="Minimum value for numeric types")
    max: Optional[float] = Field(None, description="Maximum value for numeric types")
    description: str = Field(description="What this state represents")
    initial: Optional[float] = Field(None, description="Initial value")


class TemporalUpdateInfo(BaseModel):
    state_name: str = Field(description="Name of the state to update")
    update_expression: str = Field(description="Taichi expression for updating the state over time")
    description: str = Field(description="Description of the temporal behavior")


class StateAnalysisResponse(BaseModel):
    needs_states: bool = Field(description="Whether this behavior requires custom states")
    global_states: Dict[str, StateField] = Field(default_factory=dict, description="Global states needed as dictionary")
    particle_states: Dict[str, StateField] = Field(default_factory=dict, description="Per-particle states needed as dictionary")
    species_states: Dict[str, StateField] = Field(default_factory=dict, description="Per-species states needed as dictionary")


class Synthesizer:
    
    def __init__(
        self,
        model_name: str = "gemini-2.0-flash",
        tolvera_instance=None,
        api_key: Optional[str] = None
    ):
        # Load environment variables
        self._load_env()
        
        self.model_name = model_name
        self.tv = tolvera_instance
        
        # Use model factory to create the appropriate model
        from .model_factory import ModelFactory
        self.model = ModelFactory.create_model(model_name, api_key)
        self.provider = ModelFactory.get_provider_for_model(model_name)
        logger.info(f"Synthesizer using provider '{self.provider}' with model '{model_name}'")
        
        # Initialize species components
        self.species_analyzer = SpeciesAnalyzer()
        self.species_manager = SpeciesManager(tolvera_instance) if tolvera_instance else None
        
        # Initialize prompt builder
        self.prompt_builder = ContextAwarePromptBuilder()
        
        # Keep track of experts
        self.experts = []
        
    def _load_env(self):
        env_paths = [
            Path.cwd() / ".env",
            Path(__file__).parent.parent.parent.parent.parent / ".env",
        ]
        
        for env_path in env_paths:
            if env_path.exists():
                load_dotenv(env_path)
                break
    
    def _get_expert_type_guidance(self, expert_type: Optional[str]) -> str:
        """Get expert-type specific guidance for state analysis."""
        if not expert_type:
            return ""
            
        guidance_map = {
            'force': """
FORCE EXPERT CONTEXT:
Focus on physics-related states that affect forces:
- "particles chase food" → needs 'consumed' state (ti.i32) to mark eaten food
- "energy depletes over time" → needs 'energy' state (ti.f32) that affects movement
- "particles get tired" → needs 'energy' or 'stamina' state
- "magnetic attraction" → might need 'charge' state (ti.f32)
- "particles return home" → needs 'home_pos' state (ti.math.vec2)
""",
            'interaction': """
INTERACTION EXPERT CONTEXT:
Focus on relationship and detection states:
- "predator hunts prey" → needs 'hunt_radius' state (ti.f32) for detection range
- "particles form bonds" → needs 'bond_strength' or 'connection_count' states
- "species interact differently" → needs species-specific parameters
- "particles remember encounters" → needs 'last_interaction_time' state
""",
            'visual': """
VISUAL EXPERT CONTEXT:
Focus on animation and display states:
- "particles blink" → needs 'blink_timer' or 'blink_phase' state (ti.f32)
- "color changes over time" → needs 'color_phase' or 'hue_shift' state
- "particles pulse" → needs 'pulse_phase' state for animation
- "trails fade" → needs 'trail_intensity' state
""",
            'temporal_update': """
TEMPORAL UPDATE CONTEXT:
Focus on time-dependent state changes:
- "day/night cycle" → needs 'day_phase' state (ti.f32) with periodic updates
- "aging particles" → needs 'age' state (ti.f32) that increments
- "energy regeneration" → needs energy state with recovery rules
- "seasonal changes" → needs 'season' state with transitions
""",
            'utility': """
UTILITY EXPERT CONTEXT:
Focus on helper states and flags:
- "grid-based behavior" → needs 'grid_x', 'grid_y' states (ti.i32)
- "cellular automaton" → needs 'is_alive', 'neighbor_count' states
- "state machines" → needs 'current_state' enumeration
- "counters and timers" → needs accumulator states
"""
        }
        
        return guidance_map.get(expert_type, "")

    async def analyze_states_needed(
        self,
        description: str,
        expert_type: Optional[str] = None
    ) -> Dict[str, Any]:
        logger.info(f"Analyzing states needed for: {description} (type: {expert_type})")
        
        # Get trace collector
        collector = get_collector()
        
        # Build state analysis prompt with expert type context
        prompt = self.prompt_builder.build_state_analysis_prompt(description, expert_type=expert_type)
        
        # Create structured agent for state analysis
        agent = Agent(
            self.model,
            output_type=StateAnalysisResponse,
            system_prompt=f"""
## ROLE
You are an EXPERT PARTICLE SYSTEM ANALYST and COMPUTATIONAL PHYSICIST specializing in particle behavior analysis and state management. You have deep expertise in:
- Particle system architectures and state requirements
- Taichi framework and its type system (ti.f32, ti.i32, ti.math.vec2)
- Force-based physics simulations and their data dependencies
- Behavioral modeling and the states required to implement complex behaviors
- Memory optimization and avoiding redundant state creation

## OBJECTIVE
Your objective is to analyze natural language behavior descriptions and determine the MINIMAL SET of custom states required to implement those behaviors, while avoiding duplication of built-in particle properties and ensuring computational efficiency.

## TASK AT HAND
For each behavior description, you must:
1. **Analyze Behavior Requirements**: Identify what data the behavior needs to track
2. **Check Built-in Properties**: Verify that required data isn't already available
3. **Categorize States**: Determine if states are global, per-particle, or per-species
4. **Specify Types and Ranges**: Choose appropriate Taichi types with realistic bounds
5. **Minimize State Creation**: Only create states that are absolutely necessary
6. **Validate Consistency**: Ensure needs_states flag matches actual state requirements

## KEY EXAMPLES

### Example 1: Simple Behavior (No Custom States)
**Input**: "particles fall with gravity"
**Analysis**: Gravity only needs pos, vel, mass (all built-in)
**Expected Output**:
```json
{{
  "needs_states": false,
  "global_states": {{}},
  "particle_states": {{}},
  "species_states": {{}}
}}
```

### Example 2: Energy-Based Behavior
**Input**: "particles lose energy over time and return home when tired"
**Analysis**: Needs energy tracking + home position memory
**Expected Output**:
```json
{{
  "needs_states": true,
  "global_states": {{}},
  "particle_states": {{
    "energy": {{
      "name": "energy",
      "type": "ti.f32", 
      "min": 0.0,
      "max": 100.0,
      "description": "Particle energy level that depletes over time",
      "initial": 80.0
    }},
    "home_pos": {{
      "name": "home_pos",
      "type": "ti.math.vec2",
      "min": 0.0,
      "max": 1.0, 
      "description": "Original position to return to when tired",
      "initial": null
    }}
  }},
  "species_states": {{}}
}}
```

### Example 3: Day/Night Cycle
**Input**: "behavior changes based on day and night cycle"
**Analysis**: Needs global time-of-day tracking
**Expected Output**:
```json
{{
  "needs_states": true,
  "global_states": {{
    "day_phase": {{
      "name": "day_phase",
      "type": "ti.f32",
      "min": 0.0,
      "max": 1.0,
      "description": "Current time of day (0.0=midnight, 0.5=noon)",
      "initial": 0.25
    }}
  }},
  "particle_states": {{}},
  "species_states": {{}}
}}
```

## SUCCESS VS. FAILURE CRITERIA

### SUCCESS CRITERIA:
✅ **Consistency Check**: needs_states=true only when states are actually created
✅ **No Duplication**: Never creates states for built-in properties (pos, vel, mass, size, species, active)
✅ **Minimal State Set**: Only creates states that are absolutely necessary
✅ **Proper Types**: Uses correct Taichi types (ti.f32, ti.i32, ti.math.vec2)
✅ **Realistic Ranges**: Min/max values make physical/logical sense
✅ **Descriptive Names**: State names clearly indicate their purpose (snake_case)
✅ **Correct Categories**: Global for system-wide, particle for per-particle, species for per-species
✅ **Sensible Defaults**: Initial values are reasonable starting points

### FAILURE CRITERIA:
❌ **Inconsistent Flags**: needs_states=true but all state dictionaries are empty
❌ **Duplicate Built-ins**: Creating states for pos, vel, mass, size, species, active
❌ **Over-Engineering**: Creating unnecessary states for simple behaviors
❌ **Wrong Types**: Using inappropriate Taichi types or Python types
❌ **Invalid Ranges**: Min > max, or ranges that don't make sense
❌ **Vague Names**: Generic names like 'state1' or 'data'
❌ **Wrong Categories**: Putting system-wide data in particle_states
❌ **Missing Descriptions**: Not explaining what each state represents

CRITICAL BUILT-IN PROPERTIES (NEVER RECREATE):
- pos, vel (position, velocity) - ti.math.vec2
- mass - ti.f32  
- size - ti.f32
- speed - ti.f32 (calculated from vel.norm())
- species - ti.i32
- active - ti.f32
- ppos, pvel (previous position/velocity) - ti.math.vec2

{self._get_expert_type_guidance(expert_type)}

STATE CATEGORIES:
- **global_states**: System-wide parameters (gravity_strength, day_phase, temperature)
- **particle_states**: Per-particle data (energy, home_pos, memory, flags) 
- **species_states**: Per-species configuration (aggression, speed_modifier, behavior_weights)

COMMON STATE PATTERNS:
- **Energy/Resource**: ti.f32, 0.0-100.0, initial=80.0
- **Memory Positions**: ti.math.vec2, 0.0-1.0 (normalized coordinates)
- **Time/Phase Cycles**: ti.f32, 0.0-1.0 (0=start, 1=end of cycle)
- **Counters**: ti.i32, 0-1000 
- **Boolean Flags**: ti.i32, 0-1 (Taichi doesn't have ti.bool)
- **System Forces**: ti.f32, 0.0-1000.0 (force magnitudes)

Your analysis must be CONSERVATIVE - only add states that are truly necessary for the behavior."""
        )
        
        # Create trace node for state analysis
        with collector.trace_node("state_analysis", "state_analysis", 
                                 description=description) as analysis_node:
            try:
                # Create nested LLM call node
                with collector.trace_node("llm_state_analysis", "llm_call",
                                         model=self.model_name) as llm_node:
                    # Run state analysis with structured output
                    result = await agent.run(prompt)
                    state_analysis = result.output
                    
                    # Log LLM call details
                    if llm_node:
                        # Create LLM data
                        from ..debug.tracing import LLMCallData
                        if hasattr(agent, '_system_prompt'):
                            system_prompt = agent._system_prompt
                        elif hasattr(agent, 'system_prompt'):
                            system_prompt = str(agent.system_prompt)
                        else:
                            system_prompt = "State analysis prompt"
                        full_prompt = f"{system_prompt}\n\n{prompt}"
                        llm_data = LLMCallData(
                            model=self.model_name,
                            provider="gemini",
                            system_prompt=system_prompt,
                            user_prompt=prompt,
                            full_prompt=full_prompt,
                            raw_response=str(result.output),
                            parsed_response={
                                "needs_states": state_analysis.needs_states,
                                "global_states": {name: state.model_dump() for name, state in state_analysis.global_states.items()},
                                "particle_states": {name: state.model_dump() for name, state in state_analysis.particle_states.items()},
                                "species_states": {name: state.model_dump() for name, state in state_analysis.species_states.items()}
                            }
                        )
                        llm_node.llm_call = llm_data
                
                logger.info(f"State analysis: needs_states={state_analysis.needs_states}, "
                           f"global={len(state_analysis.global_states)}, "
                           f"particle={len(state_analysis.particle_states)}, "
                           f"species={len(state_analysis.species_states)}")
                
                # Update trace node with results
                if analysis_node:
                    analysis_node.output_data = {
                        "needs_states": state_analysis.needs_states,
                        "global_states": len(state_analysis.global_states),
                        "particle_states": len(state_analysis.particle_states),
                        "species_states": len(state_analysis.species_states)
                    }
            
                # Convert to StateDefinition objects
                states_dict = {
                    'global': {},
                    'particle': {},
                    'species': {}
                }
                
                # Process global states
                for state_name, state_info in state_analysis.global_states.items():
                    states_dict['global'][state_name] = StateDefinition(
                        name=state_name,
                        category='global',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                # Process particle states, filtering out built-in properties
                BUILTIN_PARTICLE_PROPS = {'pos', 'vel', 'mass', 'size', 'speed', 'species', 'active', 'ppos', 'pvel'}
                for state_name, state_info in state_analysis.particle_states.items():
                    if state_name.lower() in BUILTIN_PARTICLE_PROPS:
                        logger.warning(f"Skipping built-in particle property '{state_name}' from state analysis")
                        continue
                    states_dict['particle'][state_name] = StateDefinition(
                        name=state_name,
                        category='particle',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                # Process species states
                for state_name, state_info in state_analysis.species_states.items():
                    states_dict['species'][state_name] = StateDefinition(
                        name=state_name,
                        category='species',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                logger.info(f"States needed - Global: {len(states_dict['global'])}, "
                           f"Particle: {len(states_dict['particle'])}, "
                           f"Species: {len(states_dict['species'])}")
                
                return states_dict
                
            except Exception as e:
                logger.warning(f"State analysis failed: {e}, proceeding without custom states")
                return {'global': {}, 'particle': {}, 'species': {}}
    
    async def synthesize_behavior(
        self,
        description: str,
        available_states: Optional[Dict[str, List[str]]] = None,
        context: Optional[Dict[str, Any]] = None,
        expert_name: Optional[str] = None,
        skip_state_analysis: bool = False
    ) -> BehaviorSynthesisResponse:
        logger.info(f"Synthesizing: {description}")
        
        # Get trace collector
        collector = get_collector()
        
        # Skip state analysis if context already provides states
        if skip_state_analysis or (context and context.get('states_already_created')):
            logger.info("Skipping state analysis - states already created")
            states_analysis = {'global': {}, 'particle': {}, 'species': {}}
        else:
            # First, analyze what states are needed
            states_analysis = await self.analyze_states_needed(description)
        
        # Flatten state definitions for the response
        states_needed_list = []
        for category in ['global', 'particle', 'species']:
            if category in states_analysis:
                for state_def in states_analysis[category].values():
                    states_needed_list.append(state_def)
        
        # Update available_states to include both existing and new states
        if available_states is None:
            available_states = {'global': [], 'particle': [], 'species': [], 'temporal': []}
        else:
            # Ensure all categories exist
            for category in ['global', 'particle', 'species', 'temporal']:
                if category not in available_states:
                    available_states[category] = []
        
        # Add analyzed states to available states for prompt
        for category in ['global', 'particle', 'species', 'temporal']:
            if category in states_analysis:
                for state_name in states_analysis[category].keys():
                    if state_name not in available_states[category]:
                        available_states[category].append(state_name)
        
        # Analyze species from description
        species_info = self.species_analyzer.analyze(description)
        logger.info(f"Detected {species_info.total_count} species from description")
        
        # Get species context for prompt
        species_context = ""
        if self.species_manager:
            species_context = self.species_manager.get_species_context_for_prompts(species_info)
        
        # Log available states for debugging
        logger.info(f"Available states for synthesis: {available_states}")
        
        # Build comprehensive prompt using ContextAwarePromptBuilder
        base_prompt = self.prompt_builder.build_synthesis_prompt(
            description=description,
            available_states=available_states,
            constrained=False,  # We want direct code generation
            context=context  # Pass context to prompt builder
        )
        
        # Add species context if available
        if species_context:
            system_prompt = base_prompt + f"\n\n## SPECIES CONTEXT\n{species_context}\n"
        else:
            system_prompt = base_prompt
        
        # Add specific instructions for expert functions
        system_prompt += f"""
## EXPERT FUNCTION REQUIREMENTS
Generate a complete Taichi expert function.
Force experts: (pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2
Interaction experts: (p1: ti.template(), p2: ti.template()) -> ti.math.vec2
Drawing/Visual experts: () # NO PARAMETERS, NO RETURN TYPE - pure drawing function

Species IDs range from 0 to {species_info.total_count - 1}.

## VISUAL/DRAWING EXPERT SYNTHESIS
For pure drawing behaviors (e.g., "draw a red rectangle"):
1. Generate a @ti.func expert that performs the drawing
2. Use tv.px drawing operations (rect, circle, line, etc.)
3. DO NOT return anything - void function, no return statement
4. Drawing operations should use screen coordinates
5. NO PARAMETERS - drawing functions take no arguments

Example visual expert WITH temporal state:
@ti.func
def draw_rectangle():
    # CRITICAL: Time-based animation states are now in llm_global!
    # For oscillating/blinking effects, check global states
    phase = tv.s.llm_global.field[0].phase  # Access animation state from global
    
    # Draw a red rectangle with oscillating opacity
    x = tv.x // 2 - 100
    y = tv.y // 2 - 50
    width = 200
    height = 100
    opacity = ti.abs(ti.sin(phase * 3.14159 * 2))
    color = ti.math.vec4(1.0, 0.0, 0.0, opacity)
    tv.px.rect(x, y, width, height, color)
    # No return statement - this is a void function

Example visual expert WITHOUT temporal state (fallback to frame counter):
@ti.func
def draw_rectangle():
    # No temporal states available, use frame counter
    frame = tv.ctx.i[None]
    phase = (frame % 150) / 150.0  # 2.5 second cycle at 60fps
    
    # Draw with oscillating opacity
    x = tv.x // 2 - 100
    y = tv.y // 2 - 50
    width = 200
    height = 100
    opacity = ti.abs(ti.sin(phase * 3.14159 * 2))
    color = ti.math.vec4(1.0, 0.0, 0.0, opacity)
    tv.px.rect(x, y, width, height, color)

## HELPER FUNCTION SYNTHESIS
If your expert needs complex operations, you SHOULD generate helper functions.
RULES FOR HELPERS:
1. Generate helpers for operations like finding nearest entities, computing distances, etc.
2. ANY HELPER YOU GENERATE MUST BE CALLED BY YOUR EXPERT - no unused helpers!
3. Helpers should be @ti.func functions that can be called from the expert
4. Include helpers in the 'helper_functions' field of your response
5. Expert code MUST call the helpers it generates

COMMON HELPERS TO GENERATE:
- For food/resource behaviors: generate consume_food helper
- For toroidal worlds: generate wrap_distance helper  
- For wandering: generate random_wander helper
- For finding targets: generate find_nearest_target helper

Example helpers for food consumption:
helper_functions: [
    {{
        "name": "consume_food",
        "code": "@ti.func\ndef consume_food(particle_idx: ti.i32, consumption_radius: ti.f32) -> ti.i32:\n    '''Check for food particles to consume'''\n    consumed = 0\n    my_pos = tv.p.field[particle_idx].pos\n    for j in range(tv.pn):\n        if tv.p.field[j].species == 2 and tv.p.field[j].active > 0:  # Food is species 2\n            dist = (tv.p.field[j].pos - my_pos).norm()\n            if dist < consumption_radius:\n                tv.p.field[j].active = 0.0  # Consume it\n                consumed = 1\n                break\n    return consumed"
    }},
    {{
        "name": "wrap_distance", 
        "code": "@ti.func\ndef wrap_distance(p1: ti.math.vec2, p2: ti.math.vec2) -> ti.math.vec2:\n    '''Calculate shortest vector in toroidal world'''\n    diff = p2 - p1\n    if ti.abs(diff.x) > tv.x * 0.5:\n        if diff.x > 0:\n            diff.x -= tv.x\n        else:\n            diff.x += tv.x\n    if ti.abs(diff.y) > tv.y * 0.5:\n        if diff.y > 0:\n            diff.y -= tv.y\n        else:\n            diff.y += tv.y\n    return diff"
    }}
]

Then in expert code:
# Check for food consumption
if species == 0 or species == 1:  # Consumers
    consumed = consume_food(particle_idx, 5.0)
    
# Use wrapped distance for toroidal topology
diff = wrap_distance(pos, target_pos)
dist = diff.norm()
if dist > 0.001:
    force = (diff / dist) * 250.0

## CRITICAL TAICHI RULES - THESE PATTERNS WILL CRASH IF WRONG:

### VECTOR OPERATIONS - USE CORRECT SYNTAX:
❌ WRONG - These methods DON'T EXIST and will crash:
```python
vec.normalized()  # ERROR: 'vec2' has no attribute 'normalized'
ti.Vector([x,y]).norm()  # ERROR: 'Vector' has no attribute 'norm'
```

✅ CORRECT - Use these patterns:
```python
# For ti.math.vec2 (PREFERRED in Tölvera):
force = ti.math.vec2(0.0, 0.0)
diff = p2.pos - p1.pos
dist = diff.norm()  # Works for ti.math.vec2
if dist > 0.001:  # ALWAYS check before division
    direction = diff / dist  # Manual normalization

# Alternative with ti.math functions:
direction = ti.math.normalize(diff)  # Built-in
length = ti.math.length(diff)  # Built-in
```

### MATH FUNCTIONS - USE TAICHI VERSIONS:
❌ WRONG:
```python
import math
angle = math.sin(t)  # ERROR in Taichi scope
```

✅ CORRECT:
```python
angle = ti.sin(t)
dist = ti.sqrt(x*x + y*y)
cos_val = ti.cos(angle)
random_val = ti.random()  # NOT random.random()
```

1. USE CORRECT VARIABLE NAMES - particle_idx NOT i:
❌ WRONG - Using undefined 'i' variable:
```python
for j in range(tv.pn):
    if i != j:  # ERROR: NameError: name 'i' is not defined
```

✅ CORRECT - Use the particle_idx parameter:
```python
def expert_function(pos, vel, mass, species, particle_idx):
    for j in range(tv.pn):
        if particle_idx != j:  # CORRECT: use the parameter
```

IMPORTANT: The current particle's index is passed as 'particle_idx' parameter, never as 'i'!

2. NEVER RETURN INSIDE CONDITIONALS - THIS IS THE #1 CAUSE OF CRASHES:

❌ WRONG - THESE EXACT PATTERNS CRASH WITH "Return inside non-static if":
```python
# Example 1: Early return for species check - CRASHES!
if species == 0:
    return ti.math.vec2(0.0, 0.0)  # CRASH!

# Example 2: Predator that doesn't hunt - CRASHES!
if species != 1:  # If not a predator
    return ti.math.vec2(0.0, 0.0)  # CRASH!
    
# Example 3: Multiple returns in branches - CRASHES!
if species == 0:
    return chase_force  # CRASH!
else:
    return flee_force  # CRASH!
```

✅ CORRECT - ALWAYS USE THESE PATTERNS:
```python
# Example 1: Predator hunt behavior - CORRECT PATTERN
@ti.func
def predator_hunt(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # ALWAYS declare result variable FIRST
    force = ti.math.vec2(0.0, 0.0)  # Default: no force
    
    # Check species and MODIFY force, don't return!
    if species == 0:  # Only predators hunt
        hunt_radius = 150.0
        nearest_prey = -1
        min_dist = hunt_radius
        
        for j in range(tv.pn):
            if tv.p.field[j].species == 1:  # Look for prey
                dist = (tv.p.field[j].pos - pos).norm()
                if dist < min_dist:
                    min_dist = dist
                    nearest_prey = j
        
        if nearest_prey != -1:
            direction = (tv.p.field[nearest_prey].pos - pos).normalized()
            force = direction * 300.0  # Set force, don't return!
    
    # SINGLE RETURN at the END
    return force

# Example 2: Prey flee behavior - CORRECT PATTERN  
@ti.func
def prey_flee(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # Declare result FIRST
    flee_force = ti.math.vec2(0.0, 0.0)
    
    # Only prey flee (species 1)
    if species == 1:
        for j in range(tv.pn):
            if tv.p.field[j].species == 0:  # Check for predators
                diff = pos - tv.p.field[j].pos
                dist = diff.norm()
                if dist < 100.0 and dist > 0.01:
                    flee_force = diff.normalized() * 400.0
                    break  # Found a predator, flee from it
    
    # SINGLE RETURN at END
    return flee_force

# Example 3: Multi-species behavior - CORRECT PATTERN
@ti.func  
def species_behavior(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # ALWAYS start with default result
    result = ti.math.vec2(0.0, 0.0)
    
    # Use if/elif to set result, NEVER return inside!
    if species == 0:
        # Predator behavior
        result = calculate_hunt_force(pos, vel)  # Set result
    elif species == 1:
        # Prey behavior  
        result = calculate_flee_force(pos, vel)  # Set result
    elif species == 2:
        # Neutral behavior
        result = calculate_wander_force(pos, vel)  # Set result
    
    # ONLY ONE RETURN at the very END
    return result
```

REMEMBER: Every single return statement MUST be at the END of the function, NEVER inside if/for/while blocks!

2. CRITICAL VARIABLE DECLARATION RULE - ALWAYS DECLARE BEFORE CONDITIONALS:
❌ WRONG - Variable defined inside conditional (COMPILATION ERROR!):
```python
if species == 0:
    alpha = 1.0      # ERROR: alpha not defined before if!
    strength = 150.0 # ERROR: strength not defined before if!
else:
    alpha = 0.0      # ERROR: these will cause compilation failure!
    strength = 50.0  # ERROR: variables must exist before conditionals!
# Using variables here will CRASH
color = ti.math.vec4(1.0, 0.0, 0.0, alpha)  # CRASH: alpha not defined
force = direction * strength  # CRASH: strength not defined
```

✅ CORRECT - ALWAYS declare variables with defaults FIRST:
```python
# ALWAYS declare ALL variables with default values BEFORE any conditionals
alpha = 0.0      # Default value declared FIRST
strength = 50.0  # Default value declared FIRST
visibility = 1.0 # Default value declared FIRST

# Now you can modify them in conditionals
if species == 0:
    alpha = 1.0       # Now we can modify existing variable
    strength = 150.0  # Now we can modify existing variable
    visibility = 0.0  # Now we can modify existing variable

# Safe to use - variables are always defined
color = ti.math.vec4(1.0, 0.0, 0.0, alpha)  # OK: alpha always defined
force = direction * strength  # OK: strength always defined
```

3. DEFINE ALL VARIABLES BEFORE USE:
❌ NEVER use undefined variables like:
if distance < undefined_radius:  # ERROR: undefined_radius not defined

✅ ALWAYS define constants at the start:
detection_radius = 100.0  # Define first
if distance < detection_radius:  # Now safe to use

3. USE ONLY AVAILABLE RESOURCES:
- Only use helper functions that are listed in AVAILABLE HELPER FUNCTIONS
- Only use states that are listed in available_states
- Define all constants and parameters locally in your function"""
        
        # Add specific expert name requirement if provided
        if expert_name:
            system_prompt += f"\n\nIMPORTANT: The function MUST be named '{expert_name}' exactly."
        
        # Initialize applies_to for later use
        applies_to = None
        
        # Check if this is a visual/drawing expert
        is_visual_expert = False
        if context and context.get('component'):
            component = context['component']
            if hasattr(component, 'expert_type') and component.expert_type == 'visual':
                is_visual_expert = True
                system_prompt += "\n\nCRITICAL: This is a VISUAL/DRAWING expert!"
                system_prompt += "\n- DO NOT return any force vector"
                system_prompt += "\n- DO NOT include '-> ti.math.vec2' in the function signature"
                system_prompt += "\n- Just perform drawing operations and end the function"
                system_prompt += "\n- Use 'if particle_idx == 0:' to draw only once per frame"
                
                # Add correct drawing API reference
                from ..context.drawing_patterns import DRAWING_API_REFERENCE
                system_prompt += "\n\nCORRECT TÖLVERA PIXELS API SIGNATURES:"
                system_prompt += "\n" + DRAWING_API_REFERENCE
                system_prompt += "\n\nIMPORTANT: Use EXACT function signatures shown above!"
                system_prompt += "\nDO NOT use incorrect signatures like tv.px.triangle(x1, y1, x2, y2, x3, y3, color)"
                system_prompt += "\nUSE CORRECT signatures like tv.px.triangle(a: vec2, b: vec2, c: vec2, rgba: vec4)"
                
                # CRITICAL: Add available states information for visual experts
                system_prompt += "\n\n## AVAILABLE STATES FOR VISUAL EXPERTS"
                system_prompt += "\nVisual experts can access these states for dynamic drawing effects:"
                
                # IMPORTANT: Order matters - check temporal first for animation states
                if available_states.get('temporal'):
                    # Temporal states are now mapped to global
                    # (Already handled in global states above)
                    system_prompt += "\nUSE THESE for time-based animations (phase, day_phase, time, etc.)"
                    system_prompt += "\nCRITICAL: For ANY oscillating/blinking/appearing/disappearing effects, use temporal states!"
                
                if available_states.get('global'):
                    system_prompt += f"\n\nGlobal states: {', '.join(available_states['global'])}"
                    system_prompt += "\nAccess with: tv.s.llm_global.field[0].STATE_NAME"
                    system_prompt += "\nNOTE: These are for global parameters, NOT for animation timing!"
                
                if available_states.get('particle'):
                    system_prompt += f"\n\nParticle states: {', '.join(available_states['particle'])}"
                    system_prompt += "\nAccess with: tv.s.llm_particle.field[particle_idx].STATE_NAME"
                    system_prompt += "\nNOTE: For drawing, you may want to loop through particles or use specific indices"
                
                if not any(available_states.values()):
                    system_prompt += "\n\nNO CUSTOM STATES AVAILABLE - use frame counter for animations:"
                    system_prompt += "\n  frame = tv.ctx.i[None]"
                    system_prompt += "\n  phase = (frame % period) / period  # For oscillations"
                else:
                    system_prompt += "\n\nIMPORTANT: Only use the states listed above! If a state doesn't exist, use frame counter instead."
        
        # If context indicates this expert is for a specific species, tell synthesizer not to check species
        if context and context.get('component') and hasattr(context['component'], 'applies_to_species'):
            applies_to = context['component'].applies_to_species
            if applies_to is not None:
                system_prompt += f"\n\nCRITICAL: This expert is specifically for species {applies_to}."
                system_prompt += "\nDO NOT check species inside the expert function!"
                system_prompt += "\nThe integration kernel will handle applying this expert only to the correct species."
                system_prompt += "\nWrite the expert assuming it's ONLY called for the intended species."
        else:
            # Fallback: Check if description mentions specific species
            desc_lower = description.lower()
            species_mentions = []
            if 'species 0' in desc_lower or 'species one' in desc_lower or 'first species' in desc_lower:
                species_mentions.append(0)
            if 'species 1' in desc_lower or 'species two' in desc_lower or 'second species' in desc_lower:
                species_mentions.append(1)
            if 'species 2' in desc_lower or 'species three' in desc_lower or 'third species' in desc_lower:
                species_mentions.append(2)
            
            # Save detected species for later use
            if species_mentions:
                applies_to = species_mentions  # Set applies_to for use later
            else:
                applies_to = None
            
            if len(species_mentions) == 1:
                system_prompt += f"\n\nDETECTED: This behavior is for species {species_mentions[0]} specifically."
                system_prompt += f"\nGenerate the expert to ONLY apply force when species == {species_mentions[0]}."
                system_prompt += "\nUse this pattern:"
                system_prompt += "\n```python"
                system_prompt += "\nforce = ti.math.vec2(0.0, 0.0)"
                system_prompt += f"\nif species == {species_mentions[0]}:"
                system_prompt += "\n    # Calculate and set force here"
                system_prompt += "\n    force = ..."
                system_prompt += "\nreturn force"
                system_prompt += "\n```"
        
        # Add previously synthesized helpers if provided in context
        if context and context.get('synthesized_helpers'):
            system_prompt += "\n\n## AVAILABLE HELPER FUNCTIONS FROM PREVIOUS EXPERTS\n"
            system_prompt += "The following helper functions have already been synthesized and are available:\n"
            for helper_name, helper_code in context['synthesized_helpers'].items():
                system_prompt += f"\n### {helper_name}:\n```python\n{helper_code}\n```\n"
            system_prompt += "\nYou can CALL these existing helpers in your expert.\n"
            system_prompt += "You can also generate NEW helpers if needed for your specific expert.\n"
        
        # Add pattern type context if provided
        if context and context.get('pattern_type'):
            system_prompt += "\n\n## PATTERN TYPE\n"
            system_prompt += f"This behavior is part of a {context['pattern_type']} pattern.\n"
            if context['pattern_type'] == 'cellular_automaton':
                system_prompt += "Use count_neighbors() and apply_rules() helpers for Game of Life logic.\n"
            elif context['pattern_type'] == 'physarum':
                system_prompt += "Use sense_pheromone(), deposit_trail(), and turn_toward_signal() for slime mold behavior.\n"
            elif context['pattern_type'] == 'ecosystem':
                system_prompt += "Use find_nearest_prey(), find_nearest_predator(), and transfer_energy() for predator-prey dynamics.\n"
        
        # Add context constraints if provided
        if context and context.get('constraints'):
            system_prompt += "\n\n## CONTEXT CONSTRAINTS\n"
            system_prompt += "The following constraints MUST be respected in your implementation:\n"
            for constraint in context['constraints']:
                system_prompt += f"- {constraint}\n"
        
        # Add previous expert information if provided
        if context and context.get('previous_experts'):
            system_prompt += "\n\n## PREVIOUS EXPERTS\n"
            system_prompt += "The following experts have already been implemented:\n"
            for prev in context['previous_experts']:
                system_prompt += f"- {prev['name']} ({prev['type']}): {prev.get('context', {})}\n"
        
        # Add shared parameters if provided
        if context and context.get('shared_parameters'):
            system_prompt += "\n\n## SHARED PARAMETERS\n"
            system_prompt += "Use these parameter values consistently across your implementation:\n"
            for param, value in context['shared_parameters'].items():
                system_prompt += f"- {param}: {value}\n"
        
        # Add explicit state usage instructions when states are available
        if any(available_states.values()):
            system_prompt += """

## IMPORTANT: USE THE AVAILABLE STATES
The following states are available and MUST be used in your implementation:
"""
            if available_states.get('global'):
                system_prompt += f"\nGlobal states: {', '.join(available_states['global'])}"
                system_prompt += "\nAccess with: tv.s.llm_global.field[0].STATE_NAME"
            if available_states.get('particle'):
                system_prompt += f"\nParticle states: {', '.join(available_states['particle'])}"
                system_prompt += "\nAccess with: tv.s.llm_particle.field[particle_idx].STATE_NAME"
            if available_states.get('species'):
                system_prompt += f"\nSpecies states: {', '.join(available_states['species'])}"
                system_prompt += "\nAccess with: tv.s.llm_species.field[species].STATE_NAME"
            # Temporal states are now part of global states (removed temporal category)
            
            system_prompt += "\n\nYour implementation MUST use these states to implement the requested behavior."
        
        # Create agent for this synthesis
        agent = Agent(
            self.model,
            output_type=TaichiCodeResponse,
            system_prompt=system_prompt
        )
        
        # User prompt
        if expert_name:
            user_prompt = f'Generate expert function named "{expert_name}" for: "{description}"'
        else:
            user_prompt = f'Generate expert function for: "{description}"'
        
        # Add behavioral guidance if provided (high-level, not specific implementation)
        if context and context.get('component_behavioral_guidance'):
            user_prompt += f"\n\nBehavioral guidance: {context['component_behavioral_guidance']}"
        elif context and context.get('component_implementation'):
            # Fallback for backward compatibility
            user_prompt += f"\n\nBehavioral guidance: {context['component_implementation']}"
        
        # Create LLM trace node
        with collector.trace_node("llm_synthesis", "llm_call", 
                                 description=description,
                                 expert_name=expert_name if expert_name else "",
                                 model=self.model_name) as llm_node:
            
            # Create LLM call data
            llm_data = LLMCallData(
                model=self.model_name,
                provider="gemini",
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                full_prompt=f"System: {system_prompt}\n\nUser: {user_prompt}"
            )
            
            try:
                # Time the API call
                start_time = time.time()
                result = await agent.run(user_prompt)
                api_duration = (time.time() - start_time) * 1000
                
                expert_data = result.output
                
                # Capture the response
                llm_data.api_call_ms = api_duration
                llm_data.raw_response = str(result)
                llm_data.parsed_response = {
                    "name": expert_data.name,
                    "description": expert_data.description,
                    "code": expert_data.code,
                    "is_interaction": expert_data.is_interaction if hasattr(expert_data, 'is_interaction') else False,
                    "helper_functions": getattr(expert_data, 'helper_functions', {}) if hasattr(expert_data, 'helper_functions') else {}
                }
                
                # Update trace node if it exists
                if llm_node:
                    llm_node.llm_call = llm_data
                    llm_node.output_data = {
                        "expert_name": expert_data.name,
                        "code_length": len(expert_data.code),
                        "is_interaction": expert_data.is_interaction
                    }
                    # Update metadata for console tracer
                    llm_node.metadata.update({
                        "model": self.model_name,
                        "prompt_length": len(system_prompt + user_prompt),
                        "response_length": len(str(result))
                    })
                
                # Create minimal expert
                expert = Expert(
                    name=expert_data.name,
                    description=expert_data.description,
                    code=expert_data.code,
                    is_interaction=expert_data.is_interaction
                )
                
                # Store it
                self.experts.append(expert)
                
                # Create proper response structure
                # We need to create the ExpertFunction with proper computation
                force_expr = VectorExpression(x="0.0", y="0.0")
                computation = ForceComputation(
                    base_force=force_expr,
                    description=expert.description if hasattr(expert, 'description') else ""
                )
                
                # Create ExpertFunction with custom to_code
                class CustomExpertFunction(ExpertFunction):
                    def __init__(self, expert: Expert, applies_to_species=None):
                        super().__init__(
                            name=expert.name,
                            description=expert.description,
                            is_interaction=expert.is_interaction,
                            computation=computation,
                            weight=expert.weight,
                            applies_to_species=applies_to_species
                        )
                        self._expert = expert
                    
                    def to_code(self) -> str:
                        return self._expert.code
                
                # Check if this expert applies to specific species based on fallback detection
                applies_to_species = applies_to if applies_to else None
                expert_func = CustomExpertFunction(expert, applies_to_species)
                
                # Create integration kernel
                kernel = IntegrationKernel(
                    single_experts=[expert.name] if not expert.is_interaction else [],
                    interaction_experts=[expert.name] if expert.is_interaction else []
                )
                
                # Create species configuration with analyzed data
                species_config = SpeciesConfiguration(
                    species_ids=species_info.species_ids if species_info.species_ids else list(range(species_info.total_count)),
                    species_names=species_info.species_names,
                    interaction_pairs=species_info.interaction_pairs,
                    species_behaviors=species_info.species_behaviors,
                    requires_all_species=species_info.requires_all_species,
                    colors={i: self.species_analyzer.get_color_for_species(i, species_info) 
                           for i in range(species_info.total_count)}
                )
                
                # Temporal updates removed - handled by individual experts
                temporal_update = None
                
                # Create response with helper functions if any
                response = BehaviorSynthesisResponse(
                    experts=[expert_func],
                    states_needed=states_needed_list,
                    species_config=species_config,
                    integration_kernel=kernel,
                    temporal_update=temporal_update
                )
                
                # Add helper functions to response if generated
                # Note: helper_functions is a Dict field which Gemini API strips, so we need to check carefully
                if hasattr(expert_data, 'helper_functions') and expert_data.helper_functions:
                    response.helper_functions = {h.name: h.code for h in expert_data.helper_functions}
                
                return response
                
            except Exception as e:
                logger.error(f"Synthesis failed: {e}")
                logger.error("Full traceback:", exc_info=True)
                # Update trace node with error if it exists
                if llm_node:
                    llm_node.error = str(e)
                    llm_node.status = "error"
                # Return default
                return self._default_response()
    
    def _default_response(self) -> BehaviorSynthesisResponse:
        
        code = """@ti.func
def drift(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    t = ti.cast(tv.ctx.i[None], ti.f32) * 0.01
    return ti.math.vec2(ti.sin(t) * 30.0, ti.cos(t) * 30.0)"""
        
        expert = Expert(
            name="drift",
            description="Simple drift",
            code=code
        )
        
        # Create proper structure
        force_expr = VectorExpression(x="0.0", y="0.0")
        computation = ForceComputation(expression=force_expr, description="drift")
        
        class CustomExpertFunction(ExpertFunction):
            def __init__(self, expert: Expert, applies_to_species=None):
                super().__init__(
                    name=expert.name,
                    description=expert.description,
                    is_interaction=False,
                    computation=computation,
                    weight=1.0,
                    applies_to_species=applies_to_species
                )
                self._expert = expert
            
            def to_code(self) -> str:
                return self._expert.code
        
        # Create integration kernel
        kernel = IntegrationKernel(
            single_experts=[expert.name],
            interaction_experts=[]
        )
        
        return BehaviorSynthesisResponse(
            experts=[CustomExpertFunction(expert, applies_to_species=None)],
            states_needed=[],
            species_config=SpeciesConfiguration(species_ids=[0]),
            integration_kernel=kernel
        )
    
    async def synthesize_initialization(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> InitializationResponse:
        """Synthesize initialization kernel based on behavior description."""
        
        # Build initialization-specific prompt
        prompt_builder = ContextAwarePromptBuilder()
        contexts = prompt_builder.detect_needed_contexts(description)
        
        # Always include initialization patterns
        contexts.add('initialization')
        if species_config and len(species_config.species_ids) > 1:
            contexts.add('species_initialization')
        
        prompt = prompt_builder.build_prompt(
            description=description,
            expert_type='initialization',
            contexts=contexts,
            species_config=species_config
        )
        
        # Add specific instructions for initialization
        system_prompt = f"""You are a Taichi expert synthesizing particle initialization code for Tölvera.
        
{prompt}

Generate a complete @ti.kernel function that initializes particles.
The function should be named 'init_particles' or similar.

IMPORTANT:
- Set tv.p.field[i].active = 1.0 for active particles
- ALWAYS set tv.p.field[i].speed = 20.0 for movement scaling
- Particle size should be 5.0-10.0 for visibility
- Species ID must be within range [0, tv.sn-1]
- Use ti.random() for randomness, not Python's random
- Initialize velocities appropriate to behavior type
"""
        
        if species_config:
            system_prompt += "\nSpecies Information:\n"
            system_prompt += f"- Total species: {len(species_config.species_ids)}\n"
            if species_config.species_names:
                for sid, name in species_config.species_names.items():
                    system_prompt += f"- Species {sid}: {name}\n"
        
        # Create agent for initialization synthesis
        agent = Agent(
            self.model,
            output_type=InitializationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize initialization
        result = await agent.run(description)
        
        return result.output
    
    async def synthesize_temporal_update(
        self,
        description: str,
        available_states: Dict[str, List[str]],
        context: Optional[Dict[str, Any]] = None
    ) -> TemporalUpdateResponse:
        """Synthesize temporal update kernel based on behavior description."""
        
        # Build temporal-specific prompt
        prompt_builder = ContextAwarePromptBuilder()
        contexts = prompt_builder.detect_needed_contexts(description)
        
        # Always include temporal patterns (even though states are global now)
        contexts.add('temporal_dynamics')  # Use the temporal_dynamics context
        contexts.add('temporal_patterns_extended')  # Include extended patterns
        
        prompt = prompt_builder.build_prompt(
            description=description,
            expert_type='temporal_update',
            contexts=contexts
        )
        
        # Format available states with temporal info
        state_info = "Available States:\n"
        temporal_states = []
        
        if 'particle' in available_states:
            state_info += f"Particle states: {', '.join(available_states['particle'])}\n"
            # Identify temporal states
            for state in available_states['particle']:
                if state in ['energy', 'age', 'phase', 'temperature', 'resources']:
                    temporal_states.append(state)
        
        if 'global' in available_states:
            state_info += f"Global states: {', '.join(available_states['global'])}\n"
        
        if 'species' in available_states:
            state_info += f"Species states: {', '.join(available_states['species'])}\n"
        
        # Temporal states are now part of global states
        # (Already included in global states above)
            # All temporal states should be included
            temporal_states.extend(available_states['temporal'])
        
        if temporal_states:
            state_info += f"\nTemporal states detected: {', '.join(temporal_states)}\n"
        
        # Enhanced system prompt with temporal guidance
        system_prompt = f"""You are a Taichi expert synthesizing temporal state updates for Tölvera.
        
{prompt}

{state_info}

Generate a complete @ti.kernel function that updates states over time.
The function should be named 'update_temporal_states'.

TEMPORAL UPDATE GUIDELINES:
1. For states that change over time:
   - energy: Deplete based on activity (vel.norm()), regenerate when resting
   - age: Increment each frame, handle lifecycle transitions
   - phase: Update based on frequency, handle wrapping
   - temperature: Apply cooling/heating with Newton's law
   - resources: Consume based on behavior, regenerate conditionally

2. Update rates based on description:
   - "slowly" → multiply by 0.999 or add/subtract 0.001
   - "gradually" → multiply by 0.99 or add/subtract 0.01
   - "quickly" → multiply by 0.95 or add/subtract 0.05
   - "rapidly" → multiply by 0.9 or add/subtract 0.1

3. Context-aware updates:
   - Make updates dependent on particle state (species, velocity, position)
   - Different species can have different update rates
   - Consider behavioral coupling (e.g., low energy affects movement)

4. Implementation structure:
   ```python
   @ti.kernel
   def update_temporal_states():
       frame = tv.ctx.i[None]
       dt = 1.0 / 60.0  # 60 FPS
       
       # Update particle states
       for i in range(tv.pn):
           if tv.p.field[i].active > 0:
               # Get states
               # Apply updates
               # Clamp values
               # Apply behavioral effects
   ```

IMPORTANT:
- Access states via tv.s.llm_particle.field[i].STATE_NAME
- Always clamp values to their valid ranges
- Only set active = 0.0 when particle truly dies (energy=0, max age)
- Consider species-specific dynamics where appropriate
"""
        
        # Add behavioral context if provided
        if context:
            if context.get('behavior_description'):
                system_prompt += f"\nBehavior Context: {context['behavior_description']}\n"
            if context.get('temporal_requirements'):
                system_prompt += f"\nTemporal Requirements: {context['temporal_requirements']}\n"
        
        # Create agent for temporal synthesis
        agent = Agent(
            self.model,
            output_type=TemporalUpdateResponse,
            system_prompt=system_prompt
        )
        
        # Generate prompt with specific temporal focus
        user_prompt = f"""Generate temporal update kernel for: {description}
        
Focus on these aspects:
1. Identify which states need temporal updates
2. Determine appropriate update rates from the description
3. Implement species-specific updates if multiple species exist
4. Add behavioral coupling where states affect particle behavior
5. Handle edge cases (death, regeneration, phase wrapping)
"""
        
        # Synthesize temporal update
        result = await agent.run(user_prompt)
        
        return result.output
    
    async def synthesize_configuration(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None
    ) -> ConfigurationResponse:
        """Synthesize Tölvera configuration based on behavior description."""
        
        system_prompt = """You are configuring Tölvera parameters based on the behavior description.
        
Generate Python code that sets up the configuration dictionary for Tölvera.
The code should define kwargs overrides based on the detected behavior type.

Example output:
```python
# Configuration for ecosystem simulation
config = {
    'sn': 2,  # 2 species detected
    'pn': 800,  # Good for ecosystem
    'width': 1920,
    'height': 1080
}
```

Consider:
- Species count from description
- Appropriate particle count for behavior type
- Screen dimensions
"""
        
        if species_config:
            system_prompt += f"\nDetected {len(species_config.species_ids)} species from description.\n"
        
        # Create agent for configuration
        agent = Agent(
            self.model,
            output_type=ConfigurationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize configuration
        result = await agent.run(description)
        
        return result.output
    
    async def synthesize_utility_expert(
        self,
        description: str,
        available_states: Dict[str, List[str]],
        context: Optional[Dict[str, Any]] = None,
        expert_type: str = 'utility'
    ) -> UtilityExpertResponse:
        """Synthesize a utility expert function that doesn't take particle parameters."""
        
        logger.info(f"Synthesizing utility expert ({expert_type}): {description}")
        
        # States should already be created by BehaviorAgent before we get here
        # Just use the available_states that were passed in
        logger.info(f"Using pre-created states: {available_states}")
        
        # Build utility-specific prompt
        prompt_builder = ContextAwarePromptBuilder()
        contexts = prompt_builder.detect_needed_contexts(description)
        
        # Add utility-specific contexts
        if 'temporal' in description.lower() or 'time' in description.lower():
            contexts.add('temporal_dynamics')
            contexts.add('temporal_patterns_extended')
        
        prompt = prompt_builder.build_prompt(
            description=description,
            expert_type=expert_type,  # Use the specific expert type
            contexts=contexts
        )
        
        # Format available states
        state_info = "Available States:\n"
        if 'particle' in available_states:
            state_info += f"Particle states: {', '.join(available_states['particle'])}\n"
        if 'global' in available_states:
            state_info += f"Global states: {', '.join(available_states['global'])}\n"
        if 'species' in available_states:
            state_info += f"Species states: {', '.join(available_states['species'])}\n"
        # Temporal states are now part of global states
        # (Already included in global states above)
        
        # Build expert-type specific guidance
        expert_guidance = ""
        if expert_type == 'temporal_update':
            expert_guidance = """
TEMPORAL UPDATE SPECIFIC RULES:
- This is a TEMPORAL UPDATE function - it updates states over time
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- Access time-based states from global: tv.s.llm_global.field[0].STATE_NAME  # (day_phase, time, etc.)
- Common pattern: increment/decrement state values over time
- Example: day_phase = (day_phase + 0.001) % 1.0

WRONG TEMPORAL UPDATE (DO NOT GENERATE):
@ti.func
def expert_name(pos, vel, mass, species, particle_idx) -> ti.math.vec2:
    # This is COMPLETELY WRONG for temporal updates!

CORRECT TEMPORAL UPDATE (GENERATE THIS):
@ti.func
def expert_name():
    # Update time-based state - NO parameters, NO return
    tv.s.llm_global.field[0].day_phase += 0.001
    if tv.s.llm_global.field[0].day_phase > 1.0:
        tv.s.llm_global.field[0].day_phase = 0.0"""
        
        elif expert_type == 'state_update':
            expert_guidance = """
STATE UPDATE SPECIFIC RULES:
- This is a STATE UPDATE function - it modifies particle or global states
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- Loop over particles internally if needed: for i in range(tv.pn):
- Access particle states: tv.s.llm_particle.field[i].STATE_NAME

CORRECT STATE UPDATE (GENERATE THIS):
@ti.func
def expert_name():
    # Update states - NO parameters, NO return
    for i in range(tv.pn):
        if tv.p.field[i].active > 0:
            tv.s.llm_particle.field[i].energy -= 0.1"""
            
        elif expert_type == 'visual':
            expert_guidance = f"""
VISUAL/DRAWING EXPERT SPECIFIC RULES:
- This is a VISUAL/DRAWING function - it creates visual effects
- ABSOLUTELY NO particle parameters: @ti.func def expert_name():
- ABSOLUTELY NO return statement - this is a void function
- DO NOT IMPORT TAICHI - it's already imported at the top of the file
- Use Pixels API: tv.px.rect(), tv.px.circle(), tv.px.line()
- Colors are ti.math.vec4(r, g, b, a) with values 0.0-1.0

CRITICAL STATE ACCESS RULES:
{state_info}

IMPORTANT: You can ONLY use the states listed above! Access patterns:
- Time-based states: tv.s.llm_global.field[0].STATE_NAME (for animations/time like day_phase, time, etc.)
- Global states: tv.s.llm_global.field[0].STATE_NAME (for global parameters)
- Particle states: tv.s.llm_particle.field[i].STATE_NAME (per-particle data)
- NEVER use tv.s.time[None] or any other made-up state access
- NEVER use llm_global for temporal/animation states!

For time-based visual effects (appearing/disappearing, pulsing, oscillating):
1. FIRST check what temporal states are ACTUALLY available from the list above
   - If 'temporal' states exist in the list, use ONLY those exact state names
   - Example: If 'phase' is listed in global states, use: tv.s.llm_global.field[0].phase
   - CRITICAL: ALL time-based states are now in llm_global!
2. If NO temporal states are available, use frame counter:
   - Access with: tv.ctx.i[None]
   - Example: visibility = ti.sin(ti.cast(tv.ctx.i[None], ti.f32) / period * 2 * ti.math.pi) > 0.0

CORRECT VISUAL EXPERT (WITH TEMPORAL STATE):
@ti.func
def expert_blinking_rectangle():
    # Use time-based state from global states
    time = tv.s.llm_global.field[0].time  # If 'time' is in global states list
    period = 2.5  # seconds
    visibility = ti.sin(2 * ti.math.pi * time / period) > 0.0
    if visibility:
        tv.px.rect(tv.x//2-50, tv.y//2-25, 100, 50, ti.math.vec4(1.0, 0.0, 0.0, 1.0))

CORRECT VISUAL EXPERT (WITHOUT TEMPORAL STATE):
@ti.func
def expert_blinking_rectangle():
    # Use frame counter as fallback
    frame = tv.ctx.i[None]
    period = 2.5 * 60  # 2.5 seconds at 60 FPS
    visibility = ti.sin(ti.cast(frame, ti.f32) / period * 2 * ti.math.pi) > 0.0
    if visibility:
        tv.px.rect(tv.x//2-50, tv.y//2-25, 100, 50, ti.math.vec4(1.0, 0.0, 0.0, 1.0))"""

        # System prompt for utility experts
        system_prompt = f"""You are a Taichi expert synthesizing {expert_type} functions for Tölvera.
        
{prompt}

{state_info}

Generate a @ti.func utility function based on the description.

{expert_guidance}

UNIVERSAL UTILITY FUNCTION RULES:
1. The function should NOT take particle parameters (pos, vel, mass, species, particle_idx)
2. Most utility functions take NO parameters at all: @ti.func def expert_name():
3. If parameters are needed, use only what's necessary (e.g., dt for time-based updates)
4. Access states directly via tv.s.llm_particle.field[i] or tv.s.llm_global.field[0]
5. Do NOT return force vectors (ti.math.vec2 or ti.Vector)
6. Most utility functions have NO return statement (void functions)
7. Use @ti.func decorator

CORRECT Examples:
@ti.func
def expert_day_phase_update():
    # Update global day phase - NO parameters, NO return
    tv.s.llm_global.field[0].day_phase += 0.001
    if tv.s.llm_global.field[0].day_phase > 1.0:
        tv.s.llm_global.field[0].day_phase = 0.0

@ti.func  
def expert_energy_depletion():
    # Deplete energy for all particles - NO parameters, NO return
    for i in range(tv.pn):
        if tv.p.field[i].active > 0:
            tv.s.llm_particle.field[i].energy -= 0.1
            if tv.s.llm_particle.field[i].energy < 0:
                tv.p.field[i].active = 0.0

The function name should start with 'expert_' followed by a descriptive name.
"""
        
        user_prompt = f"""Generate a utility expert function for: {description}

CRITICAL: The function MUST have this EXACT signature pattern:
@ti.func
def expert_{{function_name}}():
    # NO parameters in the function signature
    # Access states directly: tv.s.llm_global.field[0].day_phase  # time-based states are global
    # NO return statement (void function)
    
DO NOT include: pos, vel, mass, species, particle_idx parameters
DO NOT include: return ti.math.vec2(...) or any force return"""
        
        # Create agent for utility expert synthesis
        agent = Agent(
            self.model,
            output_type=UtilityExpertResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize utility expert
        result = await agent.run(user_prompt)
        
        return result.output
