
import os
import time
import logging
from typing import Dict, List, Optional, Any
from pathlib import Path
from dotenv import load_dotenv
from dataclasses import dataclass

from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.models.gemini import GeminiModel

from .models import (
    BehaviorSynthesisResponse,
    ExpertFunction,
    StateDefinition,
    SpeciesConfiguration,
    ForceComputation,
    VectorExpression,
    IntegrationKernel
)
from ..debug.tracing import get_collector, LLMCallData
from .species_analyzer import SpeciesAnalyzer
from .species_manager import SpeciesManager
from .prompts import ContextAwarePromptBuilder

logger = logging.getLogger(__name__)


@dataclass
class Expert:
    name: str
    description: str
    code: str
    is_interaction: bool = False
    weight: float = 1.0
    
    def to_code(self) -> str:
        return self.code


class HelperFunction(BaseModel):
    """A helper function generated by the LLM."""
    name: str = Field(description="Name of the helper function")
    code: str = Field(description="The code of the helper function")


class TaichiCodeResponse(BaseModel):
    name: str
    description: str
    code: str
    is_interaction: bool = False
    helper_functions: Optional[List[HelperFunction]] = Field(default=None, description="Helper functions generated alongside the expert")


class InitializationResponse(BaseModel):
    name: str = Field(description="Name of the initialization kernel")
    description: str = Field(description="What this initialization does")
    code: str = Field(description="Complete Taichi kernel for initialization")
    init_type: str = Field(description="Type: random, grid, clustered, ring, wave, etc.")


class TemporalUpdateResponse(BaseModel):
    name: str = Field(description="Name of the temporal update kernel")
    description: str = Field(description="What this temporal update does")
    code: str = Field(description="Complete Taichi kernel for temporal updates")
    update_type: str = Field(description="Type: energy, oscillator, growth, day_night, etc.")


class ConfigurationResponse(BaseModel):
    species_count: int = Field(description="Number of species detected")
    particle_count: int = Field(description="Recommended particle count")
    config_code: str = Field(description="Python code to configure Tölvera parameters")


class StateField(BaseModel):
    name: str = Field(description="Name of the state field")
    type: str = Field(description="Taichi type (e.g., 'ti.f32', 'ti.i32', 'ti.math.vec2')")
    min: Optional[float] = Field(None, description="Minimum value for numeric types")
    max: Optional[float] = Field(None, description="Maximum value for numeric types")
    description: str = Field(description="What this state represents")
    initial: Optional[float] = Field(None, description="Initial value")


class TemporalUpdateInfo(BaseModel):
    state_name: str = Field(description="Name of the state to update")
    update_expression: str = Field(description="Taichi expression for updating the state over time")
    description: str = Field(description="Description of the temporal behavior")


class StateAnalysisResponse(BaseModel):
    needs_states: bool = Field(description="Whether this behavior requires custom states")
    global_states: List[StateField] = Field(default_factory=list, description="Global states needed")
    particle_states: List[StateField] = Field(default_factory=list, description="Per-particle states needed")
    species_states: List[StateField] = Field(default_factory=list, description="Per-species states needed")
    temporal_updates: List[TemporalUpdateInfo] = Field(default_factory=list, description="Temporal state updates needed")


class Synthesizer:
    
    def __init__(
        self,
        model_name: str = "gemini-2.0-flash-exp",
        tolvera_instance=None,
        api_key: Optional[str] = None
    ):
        # Load environment variables
        self._load_env()
        
        # Get API key
        if not api_key:
            api_key = os.getenv("GEMINI_API_KEY")
            if not api_key:
                raise ValueError("GEMINI_API_KEY not found")
        
        self.model_name = model_name
        self.tv = tolvera_instance
        
        # Set key for Gemini
        os.environ['GEMINI_API_KEY'] = api_key
        self.model = GeminiModel(model_name)
        
        # Initialize species components
        self.species_analyzer = SpeciesAnalyzer()
        self.species_manager = SpeciesManager(tolvera_instance) if tolvera_instance else None
        
        # Initialize prompt builder
        self.prompt_builder = ContextAwarePromptBuilder()
        
        # Keep track of experts
        self.experts = []
        
    def _load_env(self):
        env_paths = [
            Path.cwd() / ".env",
            Path(__file__).parent.parent.parent.parent.parent / ".env",
        ]
        
        for env_path in env_paths:
            if env_path.exists():
                load_dotenv(env_path)
                break
    
    async def analyze_states_needed(
        self,
        description: str
    ) -> Dict[str, Any]:
        logger.info(f"Analyzing states needed for: {description}")
        
        # Get trace collector
        collector = get_collector()
        
        # Build state analysis prompt
        prompt = self.prompt_builder.build_state_analysis_prompt(description)
        
        # Create structured agent for state analysis
        agent = Agent(
            self.model,
            output_type=StateAnalysisResponse,
            system_prompt="""You are an expert at analyzing particle behaviors and determining what states they need.

CRITICAL: The following properties are ALREADY AVAILABLE on every particle and must NOT be recreated:
- pos, vel (position, velocity) - ti.math.vec2
- mass - ti.f32  
- size - ti.f32
- speed - ti.f32
- species - ti.i32
- active - ti.f32
- ppos, pvel (previous position/velocity) - ti.math.vec2

DO NOT create states for any of these existing properties!

Analyze the behavior and determine:
1. What global states are needed (system-wide parameters like gravity strength, time of day)
2. What particle states are needed (per-particle data like energy, home position - but NOT mass, pos, vel, etc.)
3. What species states are needed (per-species configuration)
4. What temporal updates are needed (states that change over time)

For physics-related states, use proper ranges:
- Gravity: 0.0 to 1000.0 (initial: 300.0)
- Forces: 0.0 to 1000.0 
- Energy: 0.0 to 100.0 (initial: 80.0)
- Time/phase: 0.0 to 1.0

For temporal behaviors like "particles lose energy over time", "fade gradually", or "day/night cycles":
- Create the appropriate state (e.g., energy as particle state, time_of_day as global state)
- Include a temporal_update entry describing how it changes over time

For temporal updates, the update_expression should be a valid Taichi expression that computes the new value.
Examples:
- For energy decay: "energy * 0.99" (multiplies current energy by 0.99)
- For time cycles: "(frame / 3600.0) % 1.0" (cycles every 3600 frames)  
- For linear decrease: "energy - 0.01" (decreases by 0.01 per frame)
- For clamped increase: "min(1.0, charge + 0.1)" (increases but caps at 1.0)

IMPORTANT: The update expression should be the RIGHT-HAND SIDE of an assignment only.
Do NOT include the full path like "tv.s.llm_particle.field[i].energy"
Just provide the expression like "energy * 0.99" or "(frame / 100.0) % 1.0"

Return a structured response with the states organized by category.
For each state, specify the Taichi type, min/max values if applicable, and a clear description.
For temporal updates, provide the state name and a VALID update expression that can be assigned."""
        )
        
        # Create trace node for state analysis
        with collector.trace_node("state_analysis", "state_analysis", 
                                 description=description) as analysis_node:
            try:
                # Create nested LLM call node
                with collector.trace_node("llm_state_analysis", "llm_call",
                                         model=self.model_name) as llm_node:
                    # Run state analysis with structured output
                    result = await agent.run(prompt)
                    state_analysis = result.output
                    
                    # Log LLM call details
                    if llm_node:
                        # Create LLM data
                        from ..debug.tracing import LLMCallData
                        if hasattr(agent, '_system_prompt'):
                            system_prompt = agent._system_prompt
                        elif hasattr(agent, 'system_prompt'):
                            system_prompt = str(agent.system_prompt)
                        else:
                            system_prompt = "State analysis prompt"
                        full_prompt = f"{system_prompt}\n\n{prompt}"
                        llm_data = LLMCallData(
                            model=self.model_name,
                            provider="gemini",
                            system_prompt=system_prompt,
                            user_prompt=prompt,
                            full_prompt=full_prompt,
                            raw_response=str(result.output),
                            parsed_response={
                                "needs_states": state_analysis.needs_states,
                                "global_states": [state.model_dump() for state in state_analysis.global_states],
                                "particle_states": [state.model_dump() for state in state_analysis.particle_states],
                                "species_states": [state.model_dump() for state in state_analysis.species_states],
                                "temporal_updates": [update.model_dump() for update in state_analysis.temporal_updates]
                            }
                        )
                        llm_node.llm_call = llm_data
                
                logger.info(f"State analysis: needs_states={state_analysis.needs_states}, "
                           f"global={len(state_analysis.global_states)}, "
                           f"particle={len(state_analysis.particle_states)}, "
                           f"species={len(state_analysis.species_states)}")
                
                # Update trace node with results
                if analysis_node:
                    analysis_node.output_data = {
                        "needs_states": state_analysis.needs_states,
                        "global_states": len(state_analysis.global_states),
                        "particle_states": len(state_analysis.particle_states),
                        "species_states": len(state_analysis.species_states),
                        "temporal_updates": len(state_analysis.temporal_updates),
                        "temporal_update_details": [
                            {
                                "state": update.state_name,
                                "expression": update.update_expression,
                                "description": update.description
                            }
                            for update in state_analysis.temporal_updates
                        ]
                    }
            
                # Convert to StateDefinition objects
                states_dict = {
                    'global': {},
                    'particle': {},
                    'species': {},
                    'temporal_updates': []
                }
                
                # Process global states
                for state_info in state_analysis.global_states:
                    states_dict['global'][state_info.name] = StateDefinition(
                        name=state_info.name,
                        category='global',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                # Process particle states, filtering out built-in properties
                BUILTIN_PARTICLE_PROPS = {'pos', 'vel', 'mass', 'size', 'speed', 'species', 'active', 'ppos', 'pvel'}
                for state_info in state_analysis.particle_states:
                    if state_info.name.lower() in BUILTIN_PARTICLE_PROPS:
                        logger.warning(f"Skipping built-in particle property '{state_info.name}' from state analysis")
                        continue
                    states_dict['particle'][state_info.name] = StateDefinition(
                        name=state_info.name,
                        category='particle',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                # Process species states
                for state_info in state_analysis.species_states:
                    states_dict['species'][state_info.name] = StateDefinition(
                        name=state_info.name,
                        category='species',
                        type=state_info.type,
                        min=state_info.min if state_info.min is not None else 0.0,
                        max=state_info.max if state_info.max is not None else 1.0,
                        description=state_info.description,
                        initial=state_info.initial
                    )
                
                # Process temporal updates
                states_dict['temporal_updates'] = state_analysis.temporal_updates
                
                logger.info(f"States needed - Global: {len(states_dict['global'])}, "
                           f"Particle: {len(states_dict['particle'])}, "
                           f"Species: {len(states_dict['species'])}, "
                           f"Temporal: {len(states_dict['temporal_updates'])}")
                
                return states_dict
                
            except Exception as e:
                logger.warning(f"State analysis failed: {e}, proceeding without custom states")
                return {'global': {}, 'particle': {}, 'species': {}, 'temporal_updates': []}
    
    async def synthesize_behavior(
        self,
        description: str,
        available_states: Optional[Dict[str, List[str]]] = None,
        context: Optional[Dict[str, Any]] = None,
        expert_name: Optional[str] = None,
        skip_state_analysis: bool = False
    ) -> BehaviorSynthesisResponse:
        logger.info(f"Synthesizing: {description}")
        
        # Get trace collector
        collector = get_collector()
        
        # Skip state analysis if context already provides states
        if skip_state_analysis or (context and context.get('states_already_created')):
            logger.info("Skipping state analysis - states already created")
            states_analysis = {'global': {}, 'particle': {}, 'species': {}, 'temporal_updates': []}
        else:
            # First, analyze what states are needed
            states_analysis = await self.analyze_states_needed(description)
        
        # Flatten state definitions for the response
        states_needed_list = []
        for category in ['global', 'particle', 'species']:
            if category in states_analysis:
                for state_def in states_analysis[category].values():
                    states_needed_list.append(state_def)
        
        # Update available_states to include both existing and new states
        if available_states is None:
            available_states = {'global': [], 'particle': [], 'species': []}
        else:
            # Ensure all categories exist
            for category in ['global', 'particle', 'species']:
                if category not in available_states:
                    available_states[category] = []
        
        # Add analyzed states to available states for prompt
        for category in ['global', 'particle', 'species']:
            if category in states_analysis:
                for state_name in states_analysis[category].keys():
                    if state_name not in available_states[category]:
                        available_states[category].append(state_name)
        
        # Analyze species from description
        species_info = self.species_analyzer.analyze(description)
        logger.info(f"Detected {species_info.total_count} species from description")
        
        # Get species context for prompt
        species_context = ""
        if self.species_manager:
            species_context = self.species_manager.get_species_context_for_prompts(species_info)
        
        # Log available states for debugging
        logger.info(f"Available states for synthesis: {available_states}")
        
        # Build comprehensive prompt using ContextAwarePromptBuilder
        base_prompt = self.prompt_builder.build_synthesis_prompt(
            description=description,
            available_states=available_states,
            constrained=False,  # We want direct code generation
            context=context  # Pass context to prompt builder
        )
        
        # Add species context if available
        if species_context:
            system_prompt = base_prompt + f"\n\n## SPECIES CONTEXT\n{species_context}\n"
        else:
            system_prompt = base_prompt
        
        # Add specific instructions for expert functions
        system_prompt += f"""
## EXPERT FUNCTION REQUIREMENTS
Generate a complete Taichi expert function.
Force experts: (pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2
Interaction experts: (p1: ti.template(), p2: ti.template()) -> ti.math.vec2
Drawing/Visual experts: () # NO PARAMETERS, NO RETURN TYPE - pure drawing function

Species IDs range from 0 to {species_info.total_count - 1}.

## VISUAL/DRAWING EXPERT SYNTHESIS
For pure drawing behaviors (e.g., "draw a red rectangle"):
1. Generate a @ti.func expert that performs the drawing
2. Use tv.px drawing operations (rect, circle, line, etc.)
3. DO NOT return anything - void function, no return statement
4. Drawing operations should use screen coordinates
5. NO PARAMETERS - drawing functions take no arguments

Example visual expert:
@ti.func
def draw_rectangle():
    # Draw a red rectangle in the middle of the screen
    x = tv.x // 2 - 100
    y = tv.y // 2 - 50
    width = 200
    height = 100
    color = ti.math.vec4(1.0, 0.0, 0.0, 1.0)
    tv.px.rect(x, y, width, height, color)
    # No return statement - this is a void function

## HELPER FUNCTION SYNTHESIS
If your expert needs complex operations, you SHOULD generate helper functions.
RULES FOR HELPERS:
1. Generate helpers for operations like finding nearest entities, computing distances, etc.
2. ANY HELPER YOU GENERATE MUST BE CALLED BY YOUR EXPERT - no unused helpers!
3. Helpers should be @ti.func functions that can be called from the expert
4. Include helpers in the 'helper_functions' field of your response
5. Expert code MUST call the helpers it generates

COMMON HELPERS TO GENERATE:
- For food/resource behaviors: generate consume_food helper
- For toroidal worlds: generate wrap_distance helper  
- For wandering: generate random_wander helper
- For finding targets: generate find_nearest_target helper

Example helpers for food consumption:
helper_functions: [
    {{
        "name": "consume_food",
        "code": "@ti.func\ndef consume_food(particle_idx: ti.i32, consumption_radius: ti.f32) -> ti.i32:\n    '''Check for food particles to consume'''\n    consumed = 0\n    my_pos = tv.p.field[particle_idx].pos\n    for j in range(tv.pn):\n        if tv.p.field[j].species == 2 and tv.p.field[j].active > 0:  # Food is species 2\n            dist = (tv.p.field[j].pos - my_pos).norm()\n            if dist < consumption_radius:\n                tv.p.field[j].active = 0.0  # Consume it\n                consumed = 1\n                break\n    return consumed"
    }},
    {{
        "name": "wrap_distance", 
        "code": "@ti.func\ndef wrap_distance(p1: ti.math.vec2, p2: ti.math.vec2) -> ti.math.vec2:\n    '''Calculate shortest vector in toroidal world'''\n    diff = p2 - p1\n    if ti.abs(diff.x) > tv.x * 0.5:\n        if diff.x > 0:\n            diff.x -= tv.x\n        else:\n            diff.x += tv.x\n    if ti.abs(diff.y) > tv.y * 0.5:\n        if diff.y > 0:\n            diff.y -= tv.y\n        else:\n            diff.y += tv.y\n    return diff"
    }}
]

Then in expert code:
# Check for food consumption
if species == 0 or species == 1:  # Consumers
    consumed = consume_food(particle_idx, 5.0)
    
# Use wrapped distance for toroidal topology
diff = wrap_distance(pos, target_pos)
dist = diff.norm()
if dist > 0.001:
    force = (diff / dist) * 100.0

## CRITICAL TAICHI RULES - THESE PATTERNS WILL CRASH IF WRONG:

### VECTOR OPERATIONS - USE CORRECT SYNTAX:
❌ WRONG - These methods DON'T EXIST and will crash:
```python
vec.normalized()  # ERROR: 'vec2' has no attribute 'normalized'
ti.Vector([x,y]).norm()  # ERROR: 'Vector' has no attribute 'norm'
```

✅ CORRECT - Use these patterns:
```python
# For ti.math.vec2 (PREFERRED in Tölvera):
force = ti.math.vec2(0.0, 0.0)
diff = p2.pos - p1.pos
dist = diff.norm()  # Works for ti.math.vec2
if dist > 0.001:  # ALWAYS check before division
    direction = diff / dist  # Manual normalization

# Alternative with ti.math functions:
direction = ti.math.normalize(diff)  # Built-in
length = ti.math.length(diff)  # Built-in
```

### MATH FUNCTIONS - USE TAICHI VERSIONS:
❌ WRONG:
```python
import math
angle = math.sin(t)  # ERROR in Taichi scope
```

✅ CORRECT:
```python
angle = ti.sin(t)
dist = ti.sqrt(x*x + y*y)
cos_val = ti.cos(angle)
random_val = ti.random()  # NOT random.random()
```

1. USE CORRECT VARIABLE NAMES - particle_idx NOT i:
❌ WRONG - Using undefined 'i' variable:
```python
for j in range(tv.pn):
    if i != j:  # ERROR: NameError: name 'i' is not defined
```

✅ CORRECT - Use the particle_idx parameter:
```python
def expert_function(pos, vel, mass, species, particle_idx):
    for j in range(tv.pn):
        if particle_idx != j:  # CORRECT: use the parameter
```

IMPORTANT: The current particle's index is passed as 'particle_idx' parameter, never as 'i'!

2. NEVER RETURN INSIDE CONDITIONALS - THIS IS THE #1 CAUSE OF CRASHES:

❌ WRONG - THESE EXACT PATTERNS CRASH WITH "Return inside non-static if":
```python
# Example 1: Early return for species check - CRASHES!
if species == 0:
    return ti.math.vec2(0.0, 0.0)  # CRASH!

# Example 2: Predator that doesn't hunt - CRASHES!
if species != 1:  # If not a predator
    return ti.math.vec2(0.0, 0.0)  # CRASH!
    
# Example 3: Multiple returns in branches - CRASHES!
if species == 0:
    return chase_force  # CRASH!
else:
    return flee_force  # CRASH!
```

✅ CORRECT - ALWAYS USE THESE PATTERNS:
```python
# Example 1: Predator hunt behavior - CORRECT PATTERN
@ti.func
def predator_hunt(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # ALWAYS declare result variable FIRST
    force = ti.math.vec2(0.0, 0.0)  # Default: no force
    
    # Check species and MODIFY force, don't return!
    if species == 0:  # Only predators hunt
        hunt_radius = 150.0
        nearest_prey = -1
        min_dist = hunt_radius
        
        for j in range(tv.pn):
            if tv.p.field[j].species == 1:  # Look for prey
                dist = (tv.p.field[j].pos - pos).norm()
                if dist < min_dist:
                    min_dist = dist
                    nearest_prey = j
        
        if nearest_prey != -1:
            direction = (tv.p.field[nearest_prey].pos - pos).normalized()
            force = direction * 300.0  # Set force, don't return!
    
    # SINGLE RETURN at the END
    return force

# Example 2: Prey flee behavior - CORRECT PATTERN  
@ti.func
def prey_flee(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # Declare result FIRST
    flee_force = ti.math.vec2(0.0, 0.0)
    
    # Only prey flee (species 1)
    if species == 1:
        for j in range(tv.pn):
            if tv.p.field[j].species == 0:  # Check for predators
                diff = pos - tv.p.field[j].pos
                dist = diff.norm()
                if dist < 100.0 and dist > 0.01:
                    flee_force = diff.normalized() * 400.0
                    break  # Found a predator, flee from it
    
    # SINGLE RETURN at END
    return flee_force

# Example 3: Multi-species behavior - CORRECT PATTERN
@ti.func  
def species_behavior(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    # ALWAYS start with default result
    result = ti.math.vec2(0.0, 0.0)
    
    # Use if/elif to set result, NEVER return inside!
    if species == 0:
        # Predator behavior
        result = calculate_hunt_force(pos, vel)  # Set result
    elif species == 1:
        # Prey behavior  
        result = calculate_flee_force(pos, vel)  # Set result
    elif species == 2:
        # Neutral behavior
        result = calculate_wander_force(pos, vel)  # Set result
    
    # ONLY ONE RETURN at the very END
    return result
```

REMEMBER: Every single return statement MUST be at the END of the function, NEVER inside if/for/while blocks!

2. DEFINE ALL VARIABLES BEFORE USE:
❌ NEVER use undefined variables like:
if distance < undefined_radius:  # ERROR: undefined_radius not defined

✅ ALWAYS define constants at the start:
detection_radius = 100.0  # Define first
if distance < detection_radius:  # Now safe to use

3. USE ONLY AVAILABLE RESOURCES:
- Only use helper functions that are listed in AVAILABLE HELPER FUNCTIONS
- Only use states that are listed in available_states
- Define all constants and parameters locally in your function"""
        
        # Add specific expert name requirement if provided
        if expert_name:
            system_prompt += f"\n\nIMPORTANT: The function MUST be named '{expert_name}' exactly."
        
        # Initialize applies_to for later use
        applies_to = None
        
        # Check if this is a visual/drawing expert
        is_visual_expert = False
        if context and context.get('component'):
            component = context['component']
            if hasattr(component, 'expert_type') and component.expert_type == 'visual':
                is_visual_expert = True
                system_prompt += "\n\nCRITICAL: This is a VISUAL/DRAWING expert!"
                system_prompt += "\n- DO NOT return any force vector"
                system_prompt += "\n- DO NOT include '-> ti.math.vec2' in the function signature"
                system_prompt += "\n- Just perform drawing operations and end the function"
                system_prompt += "\n- Use 'if particle_idx == 0:' to draw only once per frame"
        
        # If context indicates this expert is for a specific species, tell synthesizer not to check species
        if context and context.get('component') and hasattr(context['component'], 'applies_to_species'):
            applies_to = context['component'].applies_to_species
            if applies_to is not None:
                system_prompt += f"\n\nCRITICAL: This expert is specifically for species {applies_to}."
                system_prompt += "\nDO NOT check species inside the expert function!"
                system_prompt += "\nThe integration kernel will handle applying this expert only to the correct species."
                system_prompt += "\nWrite the expert assuming it's ONLY called for the intended species."
        else:
            # Fallback: Check if description mentions specific species
            desc_lower = description.lower()
            species_mentions = []
            if 'species 0' in desc_lower or 'species one' in desc_lower or 'first species' in desc_lower:
                species_mentions.append(0)
            if 'species 1' in desc_lower or 'species two' in desc_lower or 'second species' in desc_lower:
                species_mentions.append(1)
            if 'species 2' in desc_lower or 'species three' in desc_lower or 'third species' in desc_lower:
                species_mentions.append(2)
            
            # Save detected species for later use
            if species_mentions:
                applies_to = species_mentions  # Set applies_to for use later
            else:
                applies_to = None
            
            if len(species_mentions) == 1:
                system_prompt += f"\n\nDETECTED: This behavior is for species {species_mentions[0]} specifically."
                system_prompt += f"\nGenerate the expert to ONLY apply force when species == {species_mentions[0]}."
                system_prompt += "\nUse this pattern:"
                system_prompt += "\n```python"
                system_prompt += "\nforce = ti.math.vec2(0.0, 0.0)"
                system_prompt += f"\nif species == {species_mentions[0]}:"
                system_prompt += "\n    # Calculate and set force here"
                system_prompt += "\n    force = ..."
                system_prompt += "\nreturn force"
                system_prompt += "\n```"
        
        # Add previously synthesized helpers if provided in context
        if context and context.get('synthesized_helpers'):
            system_prompt += "\n\n## AVAILABLE HELPER FUNCTIONS FROM PREVIOUS EXPERTS\n"
            system_prompt += "The following helper functions have already been synthesized and are available:\n"
            for helper_name, helper_code in context['synthesized_helpers'].items():
                system_prompt += f"\n### {helper_name}:\n```python\n{helper_code}\n```\n"
            system_prompt += "\nYou can CALL these existing helpers in your expert.\n"
            system_prompt += "You can also generate NEW helpers if needed for your specific expert.\n"
        
        # Add pattern type context if provided
        if context and context.get('pattern_type'):
            system_prompt += f"\n\n## PATTERN TYPE\n"
            system_prompt += f"This behavior is part of a {context['pattern_type']} pattern.\n"
            if context['pattern_type'] == 'cellular_automaton':
                system_prompt += "Use count_neighbors() and apply_rules() helpers for Game of Life logic.\n"
            elif context['pattern_type'] == 'physarum':
                system_prompt += "Use sense_pheromone(), deposit_trail(), and turn_toward_signal() for slime mold behavior.\n"
            elif context['pattern_type'] == 'ecosystem':
                system_prompt += "Use find_nearest_prey(), find_nearest_predator(), and transfer_energy() for predator-prey dynamics.\n"
        
        # Add context constraints if provided
        if context and context.get('constraints'):
            system_prompt += "\n\n## CONTEXT CONSTRAINTS\n"
            system_prompt += "The following constraints MUST be respected in your implementation:\n"
            for constraint in context['constraints']:
                system_prompt += f"- {constraint}\n"
        
        # Add previous expert information if provided
        if context and context.get('previous_experts'):
            system_prompt += "\n\n## PREVIOUS EXPERTS\n"
            system_prompt += "The following experts have already been implemented:\n"
            for prev in context['previous_experts']:
                system_prompt += f"- {prev['name']} ({prev['type']}): {prev.get('context', {})}\n"
        
        # Add shared parameters if provided
        if context and context.get('shared_parameters'):
            system_prompt += "\n\n## SHARED PARAMETERS\n"
            system_prompt += "Use these parameter values consistently across your implementation:\n"
            for param, value in context['shared_parameters'].items():
                system_prompt += f"- {param}: {value}\n"
        
        # Add explicit state usage instructions when states are available
        if any(available_states.values()):
            system_prompt += """

## IMPORTANT: USE THE AVAILABLE STATES
The following states are available and MUST be used in your implementation:
"""
            if available_states.get('global'):
                system_prompt += f"\nGlobal states: {', '.join(available_states['global'])}"
                system_prompt += "\nAccess with: tv.s.llm_global.field[0].state_name"
            if available_states.get('particle'):
                system_prompt += f"\nParticle states: {', '.join(available_states['particle'])}"
                system_prompt += "\nAccess with: tv.s.llm_particle.field[particle_idx].state_name"
            if available_states.get('species'):
                system_prompt += f"\nSpecies states: {', '.join(available_states['species'])}"
                system_prompt += "\nAccess with: tv.s.llm_species.field[species].state_name"
            
            system_prompt += "\n\nYour implementation MUST use these states to implement the requested behavior."
        
        # Create agent for this synthesis
        agent = Agent(
            self.model,
            output_type=TaichiCodeResponse,
            system_prompt=system_prompt
        )
        
        # User prompt
        if expert_name:
            user_prompt = f'Generate expert function named "{expert_name}" for: "{description}"'
        else:
            user_prompt = f'Generate expert function for: "{description}"'
        
        # Add behavioral guidance if provided (high-level, not specific implementation)
        if context and context.get('component_behavioral_guidance'):
            user_prompt += f"\n\nBehavioral guidance: {context['component_behavioral_guidance']}"
        elif context and context.get('component_implementation'):
            # Fallback for backward compatibility
            user_prompt += f"\n\nBehavioral guidance: {context['component_implementation']}"
        
        # Create LLM trace node
        with collector.trace_node("llm_synthesis", "llm_call", 
                                 description=description,
                                 expert_name=expert_name if expert_name else "",
                                 model=self.model_name) as llm_node:
            
            # Create LLM call data
            llm_data = LLMCallData(
                model=self.model_name,
                provider="gemini",
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                full_prompt=f"System: {system_prompt}\n\nUser: {user_prompt}"
            )
            
            try:
                # Time the API call
                start_time = time.time()
                result = await agent.run(user_prompt)
                api_duration = (time.time() - start_time) * 1000
                
                expert_data = result.output
                
                # Capture the response
                llm_data.api_call_ms = api_duration
                llm_data.raw_response = str(result)
                llm_data.parsed_response = {
                    "name": expert_data.name,
                    "description": expert_data.description,
                    "code": expert_data.code,
                    "is_interaction": expert_data.is_interaction if hasattr(expert_data, 'is_interaction') else False,
                    "helper_functions": getattr(expert_data, 'helper_functions', {}) if hasattr(expert_data, 'helper_functions') else {}
                }
                
                # Update trace node if it exists
                if llm_node:
                    llm_node.llm_call = llm_data
                    llm_node.output_data = {
                        "expert_name": expert_data.name,
                        "code_length": len(expert_data.code),
                        "is_interaction": expert_data.is_interaction
                    }
                    # Update metadata for console tracer
                    llm_node.metadata.update({
                        "model": self.model_name,
                        "prompt_length": len(system_prompt + user_prompt),
                        "response_length": len(str(result))
                    })
                
                # Create minimal expert
                expert = Expert(
                    name=expert_data.name,
                    description=expert_data.description,
                    code=expert_data.code,
                    is_interaction=expert_data.is_interaction
                )
                
                # Store it
                self.experts.append(expert)
                
                # Create proper response structure
                # We need to create the ExpertFunction with proper computation
                force_expr = VectorExpression(x="0.0", y="0.0")
                computation = ForceComputation(
                    base_force=force_expr,
                    description=expert.description if hasattr(expert, 'description') else ""
                )
                
                # Create ExpertFunction with custom to_code
                class CustomExpertFunction(ExpertFunction):
                    def __init__(self, expert: Expert, applies_to_species=None):
                        super().__init__(
                            name=expert.name,
                            description=expert.description,
                            is_interaction=expert.is_interaction,
                            computation=computation,
                            weight=expert.weight,
                            applies_to_species=applies_to_species
                        )
                        self._expert = expert
                    
                    def to_code(self) -> str:
                        return self._expert.code
                
                # Check if this expert applies to specific species based on fallback detection
                applies_to_species = applies_to if applies_to else None
                expert_func = CustomExpertFunction(expert, applies_to_species)
                
                # Create integration kernel
                kernel = IntegrationKernel(
                    single_experts=[expert.name] if not expert.is_interaction else [],
                    interaction_experts=[expert.name] if expert.is_interaction else []
                )
                
                # Create species configuration with analyzed data
                species_config = SpeciesConfiguration(
                    species_ids=species_info.species_ids if species_info.species_ids else list(range(species_info.total_count)),
                    species_names=species_info.species_names,
                    interaction_pairs=species_info.interaction_pairs,
                    species_behaviors=species_info.species_behaviors,
                    requires_all_species=species_info.requires_all_species,
                    colors={i: self.species_analyzer.get_color_for_species(i, species_info) 
                           for i in range(species_info.total_count)}
                )
                
                # Create temporal update kernel if needed
                temporal_update = None
                if states_analysis.get('temporal_updates'):
                    from .models import TemporalUpdate
                    # Convert temporal updates to frame updates
                    frame_updates = {}
                    for update in states_analysis['temporal_updates']:
                        frame_updates[update.state_name] = update.update_expression
                    temporal_update = TemporalUpdate(frame_updates=frame_updates)
                
                # Create response with helper functions if any
                response = BehaviorSynthesisResponse(
                    experts=[expert_func],
                    states_needed=states_needed_list,
                    species_config=species_config,
                    integration_kernel=kernel,
                    temporal_update=temporal_update
                )
                
                # Add helper functions to response if generated
                # Note: helper_functions is a Dict field which Gemini API strips, so we need to check carefully
                if hasattr(expert_data, 'helper_functions') and expert_data.helper_functions:
                    response.helper_functions = {h.name: h.code for h in expert_data.helper_functions}
                
                return response
                
            except Exception as e:
                logger.error(f"Synthesis failed: {e}")
                logger.error(f"Full traceback:", exc_info=True)
                # Update trace node with error if it exists
                if llm_node:
                    llm_node.error = str(e)
                    llm_node.status = "error"
                # Return default
                return self._default_response()
    
    def _default_response(self) -> BehaviorSynthesisResponse:
        
        code = """@ti.func
def drift(pos: ti.math.vec2, vel: ti.math.vec2, mass: ti.f32, species: ti.i32, particle_idx: ti.i32) -> ti.math.vec2:
    t = ti.cast(tv.ctx.i[None], ti.f32) * 0.01
    return ti.math.vec2(ti.sin(t) * 30.0, ti.cos(t) * 30.0)"""
        
        expert = Expert(
            name="drift",
            description="Simple drift",
            code=code
        )
        
        # Create proper structure
        force_expr = VectorExpression(x="0.0", y="0.0")
        computation = ForceComputation(expression=force_expr, description="drift")
        
        class CustomExpertFunction(ExpertFunction):
            def __init__(self, expert: Expert, applies_to_species=None):
                super().__init__(
                    name=expert.name,
                    description=expert.description,
                    is_interaction=False,
                    computation=computation,
                    weight=1.0,
                    applies_to_species=applies_to_species
                )
                self._expert = expert
            
            def to_code(self) -> str:
                return self._expert.code
        
        # Create integration kernel
        kernel = IntegrationKernel(
            single_experts=[expert.name],
            interaction_experts=[]
        )
        
        return BehaviorSynthesisResponse(
            experts=[CustomExpertFunction(expert, applies_to_species=None)],
            states_needed=[],
            species_config=SpeciesConfiguration(species_ids=[0]),
            integration_kernel=kernel
        )
    
    async def synthesize_initialization(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> InitializationResponse:
        """Synthesize initialization kernel based on behavior description."""
        
        # Build initialization-specific prompt
        prompt_builder = ContextAwarePromptBuilder()
        contexts = prompt_builder.detect_needed_contexts(description)
        
        # Always include initialization patterns
        contexts.add('initialization')
        if species_config and len(species_config.species_ids) > 1:
            contexts.add('species_initialization')
        
        prompt = prompt_builder.build_prompt(
            description=description,
            expert_type='initialization',
            contexts=contexts,
            species_config=species_config
        )
        
        # Add specific instructions for initialization
        system_prompt = f"""You are a Taichi expert synthesizing particle initialization code for Tölvera.
        
{prompt}

Generate a complete @ti.kernel function that initializes particles.
The function should be named 'init_particles' or similar.

IMPORTANT:
- Set tv.p.field[i].active = 1.0 for active particles
- Particle size should be 5.0-10.0 for visibility
- Species ID must be within range [0, tv.sn-1]
- Use ti.random() for randomness, not Python's random
- Initialize velocities appropriate to behavior type
"""
        
        if species_config:
            system_prompt += f"\nSpecies Information:\n"
            system_prompt += f"- Total species: {len(species_config.species_ids)}\n"
            if species_config.species_names:
                for sid, name in species_config.species_names.items():
                    system_prompt += f"- Species {sid}: {name}\n"
        
        # Create agent for initialization synthesis
        agent = Agent(
            self.model,
            output_type=InitializationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize initialization
        result = await agent.run(description)
        
        return result.output
    
    async def synthesize_temporal_update(
        self,
        description: str,
        available_states: Dict[str, List[str]],
        context: Optional[Dict[str, Any]] = None
    ) -> TemporalUpdateResponse:
        """Synthesize temporal update kernel based on behavior description."""
        
        # Build temporal-specific prompt
        prompt_builder = ContextAwarePromptBuilder()
        contexts = prompt_builder.detect_needed_contexts(description)
        
        # Always include temporal patterns
        contexts.add('temporal_dynamics')  # Use the new temporal_dynamics context
        contexts.add('temporal_patterns_extended')  # Include extended patterns
        
        prompt = prompt_builder.build_prompt(
            description=description,
            expert_type='temporal_update',
            contexts=contexts
        )
        
        # Format available states with temporal info
        state_info = "Available States:\n"
        temporal_states = []
        
        if 'particle' in available_states:
            state_info += f"Particle states: {', '.join(available_states['particle'])}\n"
            # Identify temporal states
            for state in available_states['particle']:
                if state in ['energy', 'age', 'phase', 'temperature', 'resources']:
                    temporal_states.append(state)
        
        if 'global' in available_states:
            state_info += f"Global states: {', '.join(available_states['global'])}\n"
        
        if 'species' in available_states:
            state_info += f"Species states: {', '.join(available_states['species'])}\n"
        
        if temporal_states:
            state_info += f"\nTemporal states detected: {', '.join(temporal_states)}\n"
        
        # Enhanced system prompt with temporal guidance
        system_prompt = f"""You are a Taichi expert synthesizing temporal state updates for Tölvera.
        
{prompt}

{state_info}

Generate a complete @ti.kernel function that updates states over time.
The function should be named 'update_temporal_states'.

TEMPORAL UPDATE GUIDELINES:
1. For states that change over time:
   - energy: Deplete based on activity (vel.norm()), regenerate when resting
   - age: Increment each frame, handle lifecycle transitions
   - phase: Update based on frequency, handle wrapping
   - temperature: Apply cooling/heating with Newton's law
   - resources: Consume based on behavior, regenerate conditionally

2. Update rates based on description:
   - "slowly" → multiply by 0.999 or add/subtract 0.001
   - "gradually" → multiply by 0.99 or add/subtract 0.01
   - "quickly" → multiply by 0.95 or add/subtract 0.05
   - "rapidly" → multiply by 0.9 or add/subtract 0.1

3. Context-aware updates:
   - Make updates dependent on particle state (species, velocity, position)
   - Different species can have different update rates
   - Consider behavioral coupling (e.g., low energy affects movement)

4. Implementation structure:
   ```python
   @ti.kernel
   def update_temporal_states():
       frame = tv.ctx.i[None]
       dt = 1.0 / 60.0  # 60 FPS
       
       # Update particle states
       for i in range(tv.pn):
           if tv.p.field[i].active > 0:
               # Get states
               # Apply updates
               # Clamp values
               # Apply behavioral effects
   ```

IMPORTANT:
- Access states via tv.s.llm_particle.field[i].state_name
- Always clamp values to their valid ranges
- Only set active = 0.0 when particle truly dies (energy=0, max age)
- Consider species-specific dynamics where appropriate
"""
        
        # Add behavioral context if provided
        if context:
            if context.get('behavior_description'):
                system_prompt += f"\nBehavior Context: {context['behavior_description']}\n"
            if context.get('temporal_requirements'):
                system_prompt += f"\nTemporal Requirements: {context['temporal_requirements']}\n"
        
        # Create agent for temporal synthesis
        agent = Agent(
            self.model,
            output_type=TemporalUpdateResponse,
            system_prompt=system_prompt
        )
        
        # Generate prompt with specific temporal focus
        user_prompt = f"""Generate temporal update kernel for: {description}
        
Focus on these aspects:
1. Identify which states need temporal updates
2. Determine appropriate update rates from the description
3. Implement species-specific updates if multiple species exist
4. Add behavioral coupling where states affect particle behavior
5. Handle edge cases (death, regeneration, phase wrapping)
"""
        
        # Synthesize temporal update
        result = await agent.run(user_prompt)
        
        return result.output
    
    async def synthesize_configuration(
        self,
        description: str,
        species_config: Optional[SpeciesConfiguration] = None
    ) -> ConfigurationResponse:
        """Synthesize Tölvera configuration based on behavior description."""
        
        system_prompt = """You are configuring Tölvera parameters based on the behavior description.
        
Generate Python code that sets up the configuration dictionary for Tölvera.
The code should define kwargs overrides based on the detected behavior type.

Example output:
```python
# Configuration for ecosystem simulation
config = {
    'sn': 2,  # 2 species detected
    'pn': 800,  # Good for ecosystem
    'width': 1920,
    'height': 1080
}
```

Consider:
- Species count from description
- Appropriate particle count for behavior type
- Screen dimensions
"""
        
        if species_config:
            system_prompt += f"\nDetected {len(species_config.species_ids)} species from description.\n"
        
        # Create agent for configuration
        agent = Agent(
            self.model,
            output_type=ConfigurationResponse,
            system_prompt=system_prompt
        )
        
        # Synthesize configuration
        result = await agent.run(description)
        
        return result.output
