"""
This module accumulates successful Taichi kernels and functions generated by the LLM.
"""

import re
import uuid
import json
import logging
from datetime import datetime
from typing import Dict, Any, Optional, List
from pathlib import Path

logger = logging.getLogger(__name__)


class KernelAccumulator:

    def __init__(self, repository_path: str = "generated_kernels.py"):
        self.repository_path = Path(repository_path)
        self._ensure_repository_exists()

    # This is only if the file doesn't exist
    def _ensure_repository_exists(self):
        if not self.repository_path.exists():
            header = '''"""
                Generated Taichi Kernels Repository
                """

                import taichi as ti
                import tolvera as tv
                import numpy as np
                from math import pi, sqrt, sin, cos, tan, atan2
                '''
            self.repository_path.write_text(header)
            logger.info(f"Created kernel repository at {self.repository_path}")

    def save_kernel(self,
                    code: str,
                    prompt: str,
                    model: str,
                    kernel_type: str = "expert",
                    additional_metadata: Optional[Dict[str, Any]] = None) -> str:
        """
        Save a successful kernel to the repository with metadata.

        Args:
            code: The validated Taichi kernel/function code
            prompt: The original prompt that generated this kernel
            model: The model name used for generation
            kernel_type: Type of kernel ("expert" or "integration")
            additional_metadata: Any additional metadata to include

        Returns:
            The UUID assigned to this kernel
        """
        kernel_uuid = str(uuid.uuid4())
        timestamp = datetime.utcnow().isoformat()

        # Extract function name from code
        name_match = re.search(r'def\s+(\w+)', code)
        if not name_match:
            logger.error("Could not extract function name from code")
            return ""

        original_name = name_match.group(1)

        # Create unique function name
        unique_name = f"{original_name}_{kernel_uuid.replace('-', '_')[:8]}"

        # Replace function name in code so it doesn't overlap with one another
        code_with_unique_name = re.sub(
            r'def\s+' + re.escape(original_name) + r'\b',
            f'def {unique_name}',
            code
        )

        metadata = {
            "uuid": kernel_uuid,
            "original_name": original_name,
            "prompt": prompt,
            "model": model,
            "kernel_type": kernel_type,
            "timestamp": timestamp,
        }

        if additional_metadata:
            metadata.update(additional_metadata)

        docstring = f'''    """
    Generated {kernel_type} kernel

    Metadata:
    - UUID: {kernel_uuid}
    - Original Name: {original_name}
    - Prompt: {json.dumps(prompt)}
    - Model: {model}
    - Type: {kernel_type}
    - Generated: {timestamp}
    '''

        if additional_metadata:
            for key, value in additional_metadata.items():
                docstring += f"\n    - {key}: {json.dumps(value) if isinstance(value, (dict, list)) else value}"

        docstring += '\n    """'

        lines = code_with_unique_name.split('\n')
        for i, line in enumerate(lines):
            if line.strip().startswith('def ') and ':' in line:
                lines.insert(i + 1, docstring)
                break

        final_code = '\n'.join(lines)

        # Save to repo
        with self.repository_path.open('a') as f:
            f.write('\n\n')
            f.write(final_code)
            f.write('\n')

        logger.info(
            f"Saved kernel {unique_name} (original: {original_name}) with UUID {kernel_uuid}")

        return kernel_uuid

    # Not doing anything right now and not tested!  TODO: refactor when loading kernals for the LLM to use here
    def load_kernels(self) -> List[Dict[str, Any]]:
        if not self.repository_path.exists():
            return []

        content = self.repository_path.read_text()

        kernels = []

        pattern = r'(@ti\.\w+\s*\n)?def\s+(\w+).*?:\s*\n\s*"""(.*?)"""'
        matches = re.finditer(pattern, content, re.DOTALL)

        for match in matches:
            decorator = match.group(1) or ""
            func_name = match.group(2)
            docstring = match.group(3)

            metadata = {
                "function_name": func_name,
                "has_decorator": bool(decorator.strip())
            }

            for line in docstring.split('\n'):
                line = line.strip()
                if line.startswith('- UUID:'):
                    metadata['uuid'] = line.split(':', 1)[1].strip()
                elif line.startswith('- Original Name:'):
                    metadata['original_name'] = line.split(':', 1)[1].strip()
                elif line.startswith('- Prompt:'):
                    try:
                        metadata['prompt'] = json.loads(
                            line.split(':', 1)[1].strip())
                    except BaseException:
                        metadata['prompt'] = line.split(':', 1)[1].strip()
                elif line.startswith('- Model:'):
                    metadata['model'] = line.split(':', 1)[1].strip()
                elif line.startswith('- Type:'):
                    metadata['kernel_type'] = line.split(':', 1)[1].strip()
                elif line.startswith('- Generated:'):
                    metadata['timestamp'] = line.split(':', 1)[1].strip()

            kernels.append(metadata)

        return kernels

    # TODO: Leverage this when generating kernals...but right now it's not
    # doing anything.
    def search_kernels(self, query: str) -> List[Dict[str, Any]]:
        all_kernels = self.load_kernels()
        query_lower = query.lower()

        matches = []
        for kernel in all_kernels:
            prompt = kernel.get('prompt', '')
            if isinstance(prompt, str) and query_lower in prompt.lower():
                matches.append(kernel)
                continue

            if query_lower in kernel.get('original_name', '').lower():
                matches.append(kernel)
                continue

            if query_lower in kernel.get('function_name', '').lower():
                matches.append(kernel)

        return matches
