"""
Expert management for dynamically generated behaviors.

This module provides the basic structure for managing experts without any pre-built templates. All experts are generated by the LLM.
"""

from typing import Dict, List, Any
from .poe_core import SimpleProgrammaticExpert
import logging

logger = logging.getLogger(__name__)


class ExpertManager:

    def __init__(self):
        self.experts = {}
        logger.info(
            "Initialized ExpertManager - no templates, only LLM-generated experts")

    def add_expert(self, name: str, expert: SimpleProgrammaticExpert):
        self.experts[name] = expert
        logger.info(f"Added dynamic expert: {name}")

    def get_expert(self, name: str) -> SimpleProgrammaticExpert:
        if name in self.experts:
            return self.experts[name]
        raise ValueError(
            f"Expert '{name}' not found. Available: {list(self.experts.keys())}")

    def list_experts(self) -> List[str]:
        return list(self.experts.keys())

    def clear_all(self):
        self.experts.clear()
        logger.info("Cleared all experts")

    def get_expert_info(self) -> List[Dict[str, Any]]:
        return [{
            "name": name,
            "weight": expert.weight,
            "metadata": expert.metadata
        } for name, expert in self.experts.items()]
