"""
Simplified Product of Experts (PoE) Core Implementation

This module implements the core PoE system for Tölvera particle behaviors
using dynamically generated LLM code without templates or fallbacks.
"""

import taichi as ti
import numpy as np
from typing import List, Dict, Any, Optional
import logging
import re
import time

from .poe_logger import get_logger

logger = logging.getLogger(__name__)
csv_logger = get_logger()


class SimpleProgrammaticExpert:
    """A single expert program generated by LLM."""
    
    def __init__(self, name: str, code: str, weight: float = 1.0):
        self.name = name
        self.code = code
        self.weight = weight
        self.function = None
        self.metadata = {}
        
    def compile(self, namespace: Dict):
        """Compile the expert code."""
        try:
            # Log the raw code
            logger.info(f"Compiling expert {self.name}")
            logger.debug(f"Code:\n{self.code}")
            
            # Execute the code to define the function
            exec(self.code, namespace)
            
            # Extract the function name from code
            match = re.search(r'def\s+(\w+)', self.code)
            if match:
                func_name = match.group(1)
                self.function = namespace[func_name]
                logger.info(f"Successfully compiled expert {self.name}")
            else:
                logger.error(f"Could not find function definition in expert {self.name}")
        except Exception as e:
            logger.error(f"Failed to compile expert {self.name}: {e}")
            logger.error(f"Code was:\n{self.code}")
            raise


@ti.data_oriented
class PoEBehaviorSystem:
    """Simplified Product of Experts system for Tölvera particle behaviors."""
    
    def __init__(self, tolvera_instance):
        self.tv = tolvera_instance
        self.experts = []
        
        # Single force field for accumulated forces
        self.combined_forces = ti.Vector.field(2, dtype=ti.f32, shape=self.tv.pn)
        
        # Integration kernel (generated by LLM)
        self._integration_kernel = None
        self._kernel_synthesizer = None
        
        # Namespace for expert compilation
        self.namespace = {
            'ti': ti,
            'np': np,
            'tv': self.tv
        }
        
        logger.info(f"Initialized PoE system with {self.tv.pn} particles")
    
    def set_kernel_synthesizer(self, synthesizer):
        """Set the kernel synthesizer for LLM-generated integration kernels."""
        self._kernel_synthesizer = synthesizer
        logger.info("Kernel synthesizer set")
    
    async def _regenerate_kernel(self):
        """Regenerate the integration kernel based on current experts."""
        if not self._kernel_synthesizer:
            logger.warning("No kernel synthesizer available - cannot regenerate kernel")
            return False
        
        if not self.experts:
            logger.info("No experts available - clearing integration kernel")
            self._integration_kernel = None
            return True
        
        logger.info(f"Regenerating integration kernel for {len(self.experts)} experts")
        
        # Prepare expert info for kernel generation
        expert_info = [{
            'name': expert.name,
            'weight': expert.weight
        } for expert in self.experts]
        
        start_time = time.time()
        try:
            result = await self._kernel_synthesizer.synthesize_integration_kernel(expert_info)
            synthesis_time_ms = (time.time() - start_time) * 1000
            
            # Log to CSV
            csv_logger.log_synthesis_attempt(
                user_description=f"Integration kernel for {len(expert_info)} experts",
                llm_prompt=result.get("prompt", ""),
                raw_response=result.get("raw_response", ""),
                extracted_code=result.get("code", ""),
                success=result["success"],
                errors=result.get("errors", []),
                model_name=self._kernel_synthesizer.client.model_name if hasattr(self._kernel_synthesizer, 'client') else "unknown",
                expert_name=result.get("name", None),
                synthesis_time_ms=synthesis_time_ms,
                synthesis_type="kernel"
            )
            
            if result['success']:
                # Compile the kernel
                logger.info(f"Compiling integration kernel: {result['name']}")
                logger.debug(f"Kernel code:\n{result['code']}")
                
                # Add expert functions to namespace
                for expert in self.experts:
                    self.namespace[expert.name] = expert.function
                
                # Compile the kernel
                exec(result['code'], self.namespace)
                self._integration_kernel = self.namespace[result['name']]
                
                logger.info("Integration kernel successfully regenerated")
                return True
            else:
                logger.error(f"Failed to generate integration kernel: {result['errors']}")
                return False
                
        except Exception as e:
            synthesis_time_ms = (time.time() - start_time) * 1000
            logger.error(f"Error regenerating kernel: {e}")
            
            # Log the error
            csv_logger.log_synthesis_attempt(
                user_description=f"Integration kernel for {len(expert_info)} experts",
                llm_prompt="",
                raw_response="",
                extracted_code="",
                success=False,
                errors=[str(e)],
                model_name="unknown",
                expert_name=None,
                synthesis_time_ms=synthesis_time_ms,
                synthesis_type="kernel"
            )
            return False
        
    def add_expert(self, expert: SimpleProgrammaticExpert):
        """Add an expert to the system."""
        try:
            # Compile the expert
            expert.compile(self.namespace)
            self.experts.append(expert)
            logger.info(f"Added expert {expert.name} with weight {expert.weight}")
            
            # Note: Kernel regeneration happens async in integration layer
            logger.info(f"Expert {expert.name} added - kernel regeneration needed")
            
        except Exception as e:
            logger.error(f"Failed to add expert {expert.name}: {e}")
            raise
    
    def compute_and_apply_forces(self, dt: float = 0.016):
        """Compute all expert forces and apply them to particles."""
        
        if not self.experts:
            return
        
        if self._integration_kernel is None:
            logger.warning("No integration kernel available - cannot apply forces")
            return
        
        try:
            # Call the LLM-generated integration kernel
            self._integration_kernel(self.tv, self.combined_forces, dt)
        except Exception as e:
            logger.error(f"Error executing integration kernel: {e}")
            # Fallback to manual force clearing
            self.combined_forces.fill(0)
    
    def _execute_expert(self, expert: SimpleProgrammaticExpert):
        """Execute a single expert and accumulate its forces."""
        
        logger.debug(f"Executing expert {expert.name}")
        
        # Evaluate expert for each particle
        expert_forces = np.zeros((self.tv.pn, 2), dtype=np.float32)
        
        for i in range(self.tv.pn):
            if self.tv.p.field[i].active > 0:
                try:
                    # Call expert function
                    force = expert.function(self.tv, i)
                    expert_forces[i, 0] = float(force[0]) * expert.weight
                    expert_forces[i, 1] = float(force[1]) * expert.weight
                except Exception as e:
                    logger.error(f"Error in expert {expert.name} for particle {i}: {e}")
                    expert_forces[i, 0] = 0.0
                    expert_forces[i, 1] = 0.0
        
        # Transfer forces to Taichi field
        self._add_forces_from_numpy(expert_forces)
    
    @ti.kernel
    def _add_forces_from_numpy(self, forces_np: ti.types.ndarray()):
        """Add numpy forces to the combined force field."""
        for i in range(forces_np.shape[0]):
            if i < self.tv.pn:
                self.combined_forces[i][0] += forces_np[i, 0]
                self.combined_forces[i][1] += forces_np[i, 1]
    
    @ti.kernel
    def _apply_combined_forces(self, dt: ti.f32):
        """Apply accumulated forces to particle velocities."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                # Update velocity with combined force
                self.tv.p.field[i].vel += self.combined_forces[i] * dt
                
                # Apply damping
                self.tv.p.field[i].vel *= 0.98
                
                # Update position
                self.tv.p.field[i].pos += self.tv.p.field[i].vel * dt
    
    def set_expert_weight(self, expert_name: str, weight: float):
        """Update the weight of a specific expert."""
        for expert in self.experts:
            if expert.name == expert_name:
                expert.weight = weight
                logger.info(f"Updated weight for {expert_name} to {weight}")
                return
        logger.warning(f"Expert {expert_name} not found")
    
    def get_expert_info(self) -> List[Dict[str, Any]]:
        """Get information about all experts."""
        return [{
            "name": expert.name,
            "weight": expert.weight,
            "code_preview": expert.code[:200] + "..." if len(expert.code) > 200 else expert.code
        } for expert in self.experts]
    
    def clear_experts(self):
        """Remove all experts from the system."""
        self.experts.clear()
        self._integration_kernel = None
        logger.info("Cleared all experts and integration kernel")