"""Core PoE (Product of Experts) classes for Tölvera particle behaviors.

This module implements the fundamental classes for the PoE behavior system,
which generates and manages small, focused expert programs that produce
force vectors for particle motion.
"""

import taichi as ti
import numpy as np
from typing import List, Dict, Optional, Callable, Any
import re
import ast
import logging

logger = logging.getLogger(__name__)


class SimpleProgrammaticExpert:
    """A single expert program generated by LLM or defined manually.
    
    Each expert is a small, focused program that calculates forces
    for particles based on a specific behavior pattern.
    """
    
    def __init__(self, name: str, code: str, weight: float = 1.0):
        """Initialize a programmatic expert.
        
        Args:
            name: Unique identifier for this expert
            code: Python code string defining the expert's behavior
            weight: Importance weight for combining with other experts
        """
        self.name = name
        self.code = code
        self.weight = weight
        self.function = None
        self.is_compiled = False
        self.metadata = {
            "description": "",
            "category": "custom",
            "performance_cost": "unknown"
        }
        
    def compile(self, namespace: Dict[str, Any]) -> bool:
        """Compile the expert code in a controlled namespace.
        
        Args:
            namespace: Dictionary of allowed symbols (ti, np, tv, etc.)
            
        Returns:
            True if compilation successful, False otherwise
        """
        try:
            # Validate code safety first
            if not self._validate_code():
                logger.error(f"Expert {self.name} failed safety validation")
                return False
                
            # Execute code in namespace
            exec(self.code, namespace)
            
            # Extract function name from code
            match = re.search(r'def\s+(\w+)', self.code)
            if match:
                func_name = match.group(1)
                if func_name in namespace:
                    self.function = namespace[func_name]
                    self.is_compiled = True
                    logger.info(f"Successfully compiled expert: {self.name}")
                    return True
                    
            logger.error(f"Could not find function in expert {self.name}")
            return False
            
        except Exception as e:
            logger.error(f"Failed to compile expert {self.name}: {e}")
            return False
    
    def _validate_code(self) -> bool:
        """Validate expert code for safety and correctness.
        
        Returns:
            True if code is safe to execute
        """
        try:
            # Parse the code into AST
            tree = ast.parse(self.code)
            
            # Check for dangerous operations
            for node in ast.walk(tree):
                # No imports allowed
                if isinstance(node, (ast.Import, ast.ImportFrom)):
                    logger.warning(f"Import statement found in {self.name}")
                    return False
                    
                # No file operations
                if isinstance(node, ast.Name) and node.id in ['open', 'file']:
                    logger.warning(f"File operation found in {self.name}")
                    return False
                    
                # No exec/eval
                if isinstance(node, ast.Name) and node.id in ['exec', 'eval']:
                    logger.warning(f"Exec/eval found in {self.name}")
                    return False
                    
            return True
            
        except SyntaxError as e:
            logger.error(f"Syntax error in expert {self.name}: {e}")
            return False


@ti.data_oriented
class PoEBehaviorSystem:
    """Manages expert composition using Product of Experts approach.
    
    This system handles the collection of behavior experts and combines
    their outputs using the PoE methodology for emergent particle behaviors.
    """
    
    def __init__(self, tolvera_instance):
        """Initialize the PoE behavior system.
        
        Args:
            tolvera_instance: Tölvera instance to attach to
        """
        self.tv = tolvera_instance
        self.experts: List[SimpleProgrammaticExpert] = []
        self.force_accumulator = None
        self._initialized = False
        
        # Create state for forces in Tölvera's state system
        self._create_force_state()
        
        # Namespace for expert compilation
        self.namespace = {
            'ti': ti,
            'np': np,
            'Vector': ti.Vector,
            'vec2': ti.math.vec2,
            'sqrt': ti.sqrt,
            'sin': ti.sin,
            'cos': ti.cos,
            'atan2': ti.atan2,
            'max': ti.max,
            'min': ti.min,
            'abs': ti.abs,
            'random': ti.random,
        }
        
    def _create_force_state(self):
        """Create force accumulator state in Tölvera's state system."""
        try:
            # Create poe_forces state for storing per-particle forces
            self.tv.s.poe_forces = {
                "state": {
                    "fx": (ti.f32, -10.0, 10.0),
                    "fy": (ti.f32, -10.0, 10.0),
                    "weight": (ti.f32, 0.0, 1.0),
                },
                "shape": self.tv.pn,
                "randomise": False
            }
            
            # Also create a vector field for easier manipulation
            self.force_accumulator = ti.Vector.field(2, dtype=ti.f32, shape=self.tv.pn)
            
            self._initialized = True
            logger.info("Created PoE force state")
            
        except Exception as e:
            logger.error(f"Failed to create force state: {e}")
            raise
    
    def add_expert(self, expert: SimpleProgrammaticExpert) -> bool:
        """Add a behavior expert to the system.
        
        Args:
            expert: Expert to add
            
        Returns:
            True if expert was successfully added
        """
        if not expert.is_compiled:
            # Try to compile if not already done
            if not expert.compile(self.namespace):
                logger.error(f"Cannot add uncompiled expert: {expert.name}")
                return False
                
        # Check for duplicate names
        if any(e.name == expert.name for e in self.experts):
            logger.warning(f"Expert with name {expert.name} already exists")
            return False
            
        self.experts.append(expert)
        logger.info(f"Added expert: {expert.name} (weight: {expert.weight})")
        return True
    
    def remove_expert(self, name: str) -> bool:
        """Remove an expert by name.
        
        Args:
            name: Name of expert to remove
            
        Returns:
            True if expert was removed
        """
        for i, expert in enumerate(self.experts):
            if expert.name == name:
                self.experts.pop(i)
                logger.info(f"Removed expert: {name}")
                return True
        return False
    
    def get_expert(self, name: str) -> Optional[SimpleProgrammaticExpert]:
        """Get an expert by name.
        
        Args:
            name: Name of expert to retrieve
            
        Returns:
            Expert if found, None otherwise
        """
        for expert in self.experts:
            if expert.name == name:
                return expert
        return None
    
    def update_weights(self, weights: Dict[str, float]):
        """Update expert weights.
        
        Args:
            weights: Dictionary mapping expert names to new weights
        """
        for expert in self.experts:
            if expert.name in weights:
                expert.weight = weights[expert.name]
                logger.debug(f"Updated weight for {expert.name}: {expert.weight}")
    
    @ti.kernel
    def clear_forces(self):
        """Clear the force accumulator."""
        for i in self.force_accumulator:
            self.force_accumulator[i] = ti.Vector([0.0, 0.0])
            
        # Also clear the state field
        for i in self.tv.s.poe_forces.field:
            self.tv.s.poe_forces.field[i].fx = 0.0
            self.tv.s.poe_forces.field[i].fy = 0.0
            self.tv.s.poe_forces.field[i].weight = 0.0
    
    @ti.kernel
    def apply_forces_to_particles(self, dt: ti.f32, damping: ti.f32):
        """Apply accumulated forces to particle velocities.
        
        Args:
            dt: Time step
            damping: Velocity damping factor (0-1)
        """
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                # Get force from accumulator
                force = self.force_accumulator[i]
                
                # Apply force to velocity
                self.tv.p.field[i].vel += force * dt
                
                # Apply damping
                self.tv.p.field[i].vel *= damping
    
    def compute_expert_forces(self, context: Dict[str, Any]):
        """Compute forces from all active experts.
        
        This is the main method that combines expert outputs using
        the Product of Experts approach.
        
        Args:
            context: Runtime context (mouse position, time, etc.)
        """
        if not self._initialized:
            logger.error("PoE system not initialized")
            return
            
        # Don't clear forces here - let them accumulate with builtin experts
        
        # Get active experts with positive weights
        active_experts = [e for e in self.experts if e.weight > 0 and e.is_compiled]
        
        if not active_experts:
            logger.debug("No active experts")
            return
            
        # Calculate total weight for normalization
        total_weight = sum(e.weight for e in active_experts)
        
        if total_weight == 0:
            return
        
        # Apply each expert individually using generated kernels
        for expert in active_experts:
            normalized_weight = expert.weight / total_weight
            
            try:
                # Apply expert forces using dynamically created kernel
                if expert.function:
                    self._apply_single_expert(expert, normalized_weight, context)
                    logger.debug(f"Applied expert {expert.name} with weight {normalized_weight}")
            except Exception as e:
                logger.error(f"Failed to apply expert {expert.name}: {e}")
    
    def _apply_single_expert(self, expert: 'SimpleProgrammaticExpert', weight: float, context: Dict[str, Any]):
        """Apply a single expert using template-based approach.
        
        Since Taichi cannot introspect dynamically generated code, we use
        a template-based approach with parameter substitution.
        """
        try:
            # Parse expert code to extract key parameters and behavior type
            expert_type, params = self._parse_expert_code(expert.code)
            
            if expert_type == "center_attraction":
                self._apply_center_attraction_expert(
                    weight, params["center_x"], params["center_y"], params["strength"])
            elif expert_type == "mouse_attraction":
                self._apply_mouse_attraction_expert(
                    weight, params["strength"], params["radius"], 
                    context["mouse_x"], context["mouse_y"])
            elif expert_type == "boundary_repulsion":
                self._apply_boundary_repulsion_expert(
                    weight, params["margin"], params["strength"],
                    context["world_width"], context["world_height"])
            elif expert_type == "particle_separation":
                self._apply_particle_separation_expert(
                    weight, params["distance"], params["strength"])
            elif expert_type == "random_noise":
                self._apply_random_noise_expert(weight, params["strength"])
            elif expert_type == "velocity_damping":
                self._apply_velocity_damping_expert(weight, params["damping"])
            else:
                logger.warning(f"Unknown expert type: {expert_type} for expert {expert.name}")
                
        except Exception as e:
            logger.error(f"Failed to apply expert {expert.name}: {e}")
    
    def _parse_expert_code(self, code: str):
        """Parse expert code to extract behavior type and parameters."""
        # Simple heuristic parsing based on keywords in the code
        code_lower = code.lower()
        
        if "center" in code_lower and ("400.0" in code or "300.0" in code):
            # Center attraction to fixed point
            center_x = 400.0
            center_y = 300.0
            strength = 50.0
            # Try to extract actual values from code
            import re
            center_match = re.search(r'ti\.Vector\(\[(\d+\.?\d*),\s*(\d+\.?\d*)\]\)', code)
            if center_match:
                center_x = float(center_match.group(1))
                center_y = float(center_match.group(2))
            
            strength_match = re.search(r'(\d+\.?\d*)\s*/\s*dist', code)
            if strength_match:
                strength = float(strength_match.group(1))
                
            return "center_attraction", {"center_x": center_x, "center_y": center_y, "strength": strength}
            
        elif "mouse" in code_lower:
            return "mouse_attraction", {"strength": 1.0, "radius": 200.0}
            
        elif "boundary" in code_lower or "edge" in code_lower:
            return "boundary_repulsion", {"margin": 50.0, "strength": 0.5}
            
        elif "separation" in code_lower or "repel" in code_lower:
            return "particle_separation", {"distance": 30.0, "strength": 0.1}
            
        elif "random" in code_lower or "noise" in code_lower:
            return "random_noise", {"strength": 0.1}
            
        elif "damping" in code_lower or "vel" in code_lower:
            return "velocity_damping", {"damping": 0.02}
            
        # Default fallback
        return "center_attraction", {"center_x": 400.0, "center_y": 300.0, "strength": 50.0}
    
    @ti.kernel
    def _apply_center_attraction_expert(self, weight: ti.f32, center_x: ti.f32, center_y: ti.f32, strength: ti.f32):
        """Apply center attraction expert."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                pos = self.tv.p.field[i].pos
                center = ti.Vector([center_x, center_y])
                to_center = center - pos
                dist = to_center.norm()
                
                force = ti.Vector([0.0, 0.0])
                if dist > 1.0:  # Avoid singularity
                    force = to_center.normalized() * (strength / dist)
                
                self.force_accumulator[i] += force * weight
    
    @ti.kernel
    def _apply_mouse_attraction_expert(self, weight: ti.f32, strength: ti.f32, radius: ti.f32, 
                                     mouse_x: ti.f32, mouse_y: ti.f32):
        """Apply mouse attraction expert."""
        mouse_pos = ti.Vector([mouse_x, mouse_y])
        
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                pos = self.tv.p.field[i].pos
                to_mouse = mouse_pos - pos
                dist = to_mouse.norm()
                
                force = ti.Vector([0.0, 0.0])
                if dist > 1.0 and dist < radius:
                    force = to_mouse.normalized() * (strength / dist)
                
                self.force_accumulator[i] += force * weight
    
    @ti.kernel
    def _apply_boundary_repulsion_expert(self, weight: ti.f32, margin: ti.f32, strength: ti.f32,
                                       world_width: ti.f32, world_height: ti.f32):
        """Apply boundary repulsion expert."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                pos = self.tv.p.field[i].pos
                force = ti.Vector([0.0, 0.0])
                
                # Left/right boundaries
                if pos[0] < margin:
                    force[0] += strength * (margin - pos[0]) / margin
                elif pos[0] > world_width - margin:
                    force[0] -= strength * (pos[0] - (world_width - margin)) / margin
                
                # Top/bottom boundaries
                if pos[1] < margin:
                    force[1] += strength * (margin - pos[1]) / margin
                elif pos[1] > world_height - margin:
                    force[1] -= strength * (pos[1] - (world_height - margin)) / margin
                    
                self.force_accumulator[i] += force * weight
    
    @ti.kernel
    def _apply_particle_separation_expert(self, weight: ti.f32, separation_dist: ti.f32, strength: ti.f32):
        """Apply particle separation expert."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                pos_i = self.tv.p.field[i].pos
                force = ti.Vector([0.0, 0.0])
                
                for j in range(self.tv.pn):
                    if i != j and self.tv.p.field[j].active > 0:
                        pos_j = self.tv.p.field[j].pos
                        diff = pos_i - pos_j
                        dist = diff.norm()
                        
                        if 0 < dist < separation_dist:
                            # Repulsion force
                            force += diff.normalized() * (strength / dist)
                
                self.force_accumulator[i] += force * weight
    
    @ti.kernel  
    def _apply_random_noise_expert(self, weight: ti.f32, strength: ti.f32):
        """Apply random noise expert."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                force = ti.Vector([
                    (ti.random() - 0.5) * strength,
                    (ti.random() - 0.5) * strength
                ])
                self.force_accumulator[i] += force * weight
    
    @ti.kernel
    def _apply_velocity_damping_expert(self, weight: ti.f32, damping: ti.f32):
        """Apply velocity damping expert."""
        for i in self.tv.p.field:
            if self.tv.p.field[i].active > 0:
                vel = self.tv.p.field[i].vel
                force = -vel * damping
                self.force_accumulator[i] += force * weight
    
    def get_status(self) -> Dict[str, Any]:
        """Get current system status.
        
        Returns:
            Dictionary with system information
        """
        return {
            "initialized": self._initialized,
            "num_experts": len(self.experts),
            "active_experts": len([e for e in self.experts if e.weight > 0]),
            "experts": [
                {
                    "name": e.name,
                    "weight": e.weight,
                    "compiled": e.is_compiled,
                    "category": e.metadata.get("category", "unknown")
                }
                for e in self.experts
            ]
        }