"""
Simplified Product of Experts (PoE) Core Implementation

This module implements the core PoE system for Tölvera particle behaviors
using dynamically generated LLM code without templates or fallbacks.
"""

import taichi as ti
import numpy as np
from typing import List, Dict, Any, Optional
import logging
import re
import time
import linecache

from .poe_logger import get_logger

logger = logging.getLogger(__name__)
csv_logger = get_logger()


class SimpleProgrammaticExpert:
    """A single expert program generated by LLM."""
    
    def __init__(self, name: str, code: str, weight: float = 1.0):
        self.name = name
        self.code = code
        self.weight = weight
        self.function = None
        self.metadata = {}
        
    def compile(self, namespace: Dict):
        try:
            # Log the raw code
            logger.info(f"Compiling expert {self.name}")
            logger.debug(f"Code:\n{self.code}")
            
            # Execute the code to define the function
            exec(self.code, namespace)
            
            # Extract the function name from code
            match = re.search(r'def\s+(\w+)', self.code)
            if match:
                func_name = match.group(1)
                self.function = namespace[func_name]
                logger.info(f"Successfully compiled expert {self.name}")
            else:
                logger.error(f"Could not find function definition in expert {self.name}")
        except Exception as e:
            logger.error(f"Failed to compile expert {self.name}: {e}")
            logger.error(f"Code was:\n{self.code}")
            raise


@ti.data_oriented
class PoEBehaviorSystem:
    """Simplified Product of Experts system for Tölvera particle behaviors."""
    
    def __init__(self, tolvera_instance):
        self.tv = tolvera_instance
        self.experts = []
        
        # Integration kernel (generated by LLM)
        self._integration_kernel = None

        # Track generated code
        self.generated_expert_code = {}  # Dict mapping expert name -> code
        self.generated_kernel_code = None
        
        # Namespace for expert compilation
        self.namespace = {
            'ti': ti,
            'np': np,
            'tv': self.tv
        }
        
        logger.info(f"Initialized PoE system with {self.tv.pn} particles")
    
    
    async def regenerate_integration_kernel(self, synthesizer):
        """Regenerate the integration kernel based on current experts using provided synthesizer."""
        if not self.experts:
            logger.info("No experts available - clearing integration kernel")
            self._integration_kernel = None
            return True

        logger.info(f"Regenerating integration kernel for {len(self.experts)} experts")

        expert_info = [{'name': expert.name, 'weight': expert.weight} for expert in self.experts]
        
        # Collect natural language descriptions of experts for logging
        expert_descriptions = [expert.metadata.get("description", expert.name) for expert in self.experts]
        user_description_for_kernel = f"Integration kernel for experts: {'; '.join(expert_descriptions)}"

        start_time = time.time()
        try:
            result = await synthesizer.synthesize_integration_kernel(expert_info)
            synthesis_time_ms = (time.time() - start_time) * 1000

            csv_logger.log_synthesis_attempt(
                user_description=user_description_for_kernel,
                llm_prompt=result.get("prompt", ""),
                raw_response=result.get("raw_response", ""),
                extracted_code=result.get("code", ""),
                success=result["success"],
                errors=result.get("errors", []),
                model_name=synthesizer.client.model_name if hasattr(synthesizer, 'client') else "unknown",
                expert_name=result.get("name", None),
                synthesis_time_ms=synthesis_time_ms,
                synthesis_type="kernel",
                included_experts=[expert.name for expert in self.experts],
                expert_codes=self.generated_expert_code.copy()
            )

            if result['success']:
                self.generated_kernel_code = result.get('code', '')

                # Combine all expert and kernel code into a single string
                all_code = "\n\n".join([expert.code for expert in self.experts] + [self.generated_kernel_code])
                
                # Use a unique name for the fake file to avoid cache collisions
                source_name = f"<poe_generated_kernel_{time.time_ns()}>"
                
                # Put the combined code into linecache
                linecache.cache[source_name] = (len(all_code), None, [line + '\n' for line in all_code.splitlines()], source_name)

                logger.info("Compiling combined expert and kernel code")
                logger.debug(f"Combined Code:\n{all_code}")

                # Create a fresh namespace
                kernel_namespace = {'ti': ti, 'np': np, 'tv': self.tv}
                
                # Compile the combined code
                code_obj = compile(all_code, source_name, 'exec')
                exec(code_obj, kernel_namespace)
                
                self._integration_kernel = kernel_namespace[result['name']]
                
                logger.info("Integration kernel successfully regenerated")
                return True
            else:
                logger.error(f"Failed to generate integration kernel: {result['errors']}")
                return False

        except Exception as e:
            synthesis_time_ms = (time.time() - start_time) * 1000
            logger.error(f"Error regenerating kernel: {e}", exc_info=True)
            csv_logger.log_synthesis_attempt(
                user_description=f"Integration kernel for {len(expert_info)} experts",
                llm_prompt="", raw_response="", extracted_code="", success=False,
                errors=[str(e)], model_name="unknown", expert_name=None,
                synthesis_time_ms=synthesis_time_ms, synthesis_type="kernel",
                included_experts=[expert.name for expert in self.experts],
                expert_codes=self.generated_expert_code.copy()
            )
            return False
        
    def add_expert(self, expert: SimpleProgrammaticExpert):
        try:
            # Compile the expert
            expert.compile(self.namespace)
            self.experts.append(expert)

            # Track expert code
            self.generated_expert_code[expert.name] = expert.code

            logger.info(f"Added expert {expert.name} with weight {expert.weight}")
            
            # Clear integration kernel - it needs to be regenerated with new expert
            self._integration_kernel = None
            logger.info(f"Expert {expert.name} added - integration kernel invalidated and needs regeneration")
            
        except Exception as e:
            logger.error(f"Failed to add expert {expert.name}: {e}")
            raise
    
    def set_expert_weight(self, expert_name: str, weight: float):
        for expert in self.experts:
            if expert.name == expert_name:
                expert.weight = weight
                logger.info(f"Updated weight for {expert_name} to {weight}")
                return
        logger.warning(f"Expert {expert_name} not found")
    
    def get_expert_info(self) -> List[Dict[str, Any]]:
        return [{
            "name": expert.name,
            "weight": expert.weight,
            "code_preview": expert.code[:200] + "..." if len(expert.code) > 200 else expert.code
        } for expert in self.experts]
    
    def clear_experts(self):
        self.experts.clear()
        self.generated_expert_code.clear()
        self._integration_kernel = None
        logger.info("Cleared all experts and integration kernel")