"""
Context injection framework for LLM prompts.
"""

from .library_docs import (
    TOLVERA_CORE_API,
    TAICHI_ESSENTIALS
)
from .pixels_api import PIXELS_API, PIXELS_PATTERNS
from .particles_api import PARTICLES_API, PARTICLE_PATTERNS

# Backward compatibility alias
TOLVERA_PIXELS_API = PIXELS_API
from .patterns import (
    MOVEMENT_PATTERNS,
    FLOCKING_PATTERNS,
    INTERACTION_PATTERNS,
    TEMPORAL_PATTERNS,
    CELLULAR_AUTOMATA_PATTERNS,
    EMERGENT_PATTERNS
)
from .examples import EXAMPLE_EXPERTS
from .vera_patterns import VERA_PATTERNS, INTERACTION_PATTERNS_VERA
from .drawing_patterns import DRAWING_PATTERNS, DRAWING_API_REFERENCE
from .taichi_patterns import (
    TAICHI_FUNDAMENTALS,
    ARTIFICIAL_LIFE_PATTERNS,
    IML_PATTERNS
)
from .alife_patterns import (
    EVOLUTION_PATTERNS,
    ECOSYSTEM_PATTERNS,
    MORPHOGENETIC_PATTERNS,
    SWARM_INTELLIGENCE
)

__all__ = [
    'TOLVERA_CORE_API',
    'TOLVERA_PIXELS_API',
    'PIXELS_API',
    'PIXELS_PATTERNS',
    'PARTICLES_API',
    'PARTICLE_PATTERNS',
    'TAICHI_ESSENTIALS',
    'MOVEMENT_PATTERNS',
    'FLOCKING_PATTERNS',
    'INTERACTION_PATTERNS',
    'TEMPORAL_PATTERNS',
    'CELLULAR_AUTOMATA_PATTERNS',
    'EMERGENT_PATTERNS',
    'VERA_PATTERNS',
    'INTERACTION_PATTERNS_VERA',
    'TAICHI_FUNDAMENTALS',
    'ARTIFICIAL_LIFE_PATTERNS',
    'IML_PATTERNS',
    'EVOLUTION_PATTERNS',
    'ECOSYSTEM_PATTERNS',
    'MORPHOGENETIC_PATTERNS',
    'SWARM_INTELLIGENCE',
    'EXAMPLE_EXPERTS',
    'DRAWING_PATTERNS',
    'DRAWING_API_REFERENCE'
]